import { pgTable, pgEnum, text, uuid, timestamp, bigint, boolean, json } from 'drizzle-orm/pg-core';

// ─────────────────────────────────────────────────────────────────────────────
// Schema Extension for Index Protocol with IEEE P7012 Compliance + Examples
// Focus: Minimal but sufficient fields to support private file matching,
// broker trust, reasoning visibility, and informed negotiation.
// Inspired by: IEEE P7012:2025 (sections 3.3, 6.3.x, 7.1.x)
// ─────────────────────────────────────────────────────────────────────────────

//
// NEW TABLE: intentPrivacyPolicies
// Describes how private content can be used for intent matching.
// Related P7012: PrivacyPreference, PreferenceApplicability, TransparencyTerm
//
export const intentPrivacyPolicies = pgTable('intent_privacy_policies', {
    // FK to intent
    intentId: uuid('intent_id').notNull().references(() => intents.id),
  
    // Broker-level access to private file content (e.g. technical deck)
    allowBrokerFileAccess: boolean('allow_broker_file_access').notNull().default(false),
  
    // Allows embeddings to be generated from intent/file content
    allowEmbedding: boolean('allow_embedding').notNull().default(false),
  
    // Optional access condition: "Only share with nonprofit investors"
    fileAccessCondition: text('file_access_condition'),
  
    // Controls who can see the LLM-generated reasoning:
    // - 'public': in feed/search
    // - 'matchedOnly': only after opt-in
    // - 'brokerOnly': for audit/logging only
    reasoningVisibility: text('reasoning_visibility').notNull().default('public'),
  }, (table) => ({
    pk: { name: 'intent_privacy_policies_pkey', columns: [table.intentId] },
  }));
  
  
  //
  // UPDATED TABLE: intentFiles
  // Adds broker access flags and reasoning hints
  // Related P7012: DataSharingTerm, AgreementInteractionRecord
  //
  export const intentFiles = pgTable('intent_files', {
    intentId: uuid('intent_id').notNull().references(() => intents.id),
    fileId: uuid('file_id').notNull().references(() => files.id),
  
    // Allows trusted broker agents to use content to generate match reasoning
    visibleToBroker: boolean('visible_to_broker').notNull().default(false),
  
    // Allows file to be shared after both parties opt in
    visibleAfterOptIn: boolean('visible_after_opt_in').notNull().default(true),
  
    // Optional hint: "Technical overview on ZK stack"
    reasoningHint: text('reasoning_hint'),
  }, (table) => ({
    pk: { name: 'intent_files_pkey', columns: [table.intentId, table.fileId] },
  }));
  
  
  //
  // UPDATED TABLE: intentStakes
  // Adds a flag for whether reasoning used private content
  // Related P7012: AgreementNegotiationRequest, AgentBehaviour
  //
  export const intentStakes = pgTable('intent_stakes', {
    id: uuid('id').primaryKey().defaultRandom(),
  
    // Participating intents (usually 2)
    intents: text('intents').array().notNull(),
  
    // Token value used for staking match quality
    stake: bigint('stake', { mode: 'bigint' }).notNull(),
  
    // LLM- or agent-generated justification
    reasoning: text('reasoning').notNull(),
  
    // Who made this match proposal
    agentId: uuid('agent_id').notNull().references(() => agents.id),
  
    // Did the reasoning include private files?
    usedPrivateContent: boolean('used_private_content').notNull().default(false),
  
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at').defaultNow().notNull(),
  });
  
  
  // ─────────────────────────────────────────────────────────────────────────────
  // 🧪 Example 1: Founder uploads technical deck
  // ─────────────────────────────────────────────────────────────────────────────
  const intent = {
    id: 'intent-fnd-1',
    payload: 'Looking for investors in privacy-preserving AI.',
  };
  
  const file = {
    id: 'file-1',
    name: 'PrivateDeck.pdf',
    content: 'We use ZK proofs for agent coordination.',
  };
  
  const privacyPolicy = {
    intentId: 'intent-fnd-1',
    allowBrokerFileAccess: true,
    allowEmbedding: false,
    reasoningVisibility: 'matchedOnly',
    fileAccessCondition: 'Only show to verified investors',
  };
  
  const fileMeta = {
    intentId: 'intent-fnd-1',
    fileId: 'file-1',
    visibleToBroker: true,
    visibleAfterOptIn: true,
    reasoningHint: 'Detailed architecture of ZK inference layer.',
  };
  
  // ─────────────────────────────────────────────────────────────────────────────
  // 🧪 Example 2: Match reasoning generated by broker agent using private file
  // ─────────────────────────────────────────────────────────────────────────────
  const intentStake = {
    id: 'stake-xyz',
    intents: ['intent-fnd-1', 'intent-inv-2'],
    stake: 5000000n,
    agentId: 'agent-broker-1',
    reasoning: `Strong match on technical thesis. Investor mentions privacy infra;
  Founder provided deck (not shared) includes novel ZK coordination model.
  Private content reviewed. File(s) remain confidential until mutual opt-in.`,
    usedPrivateContent: true,
    createdAt: new Date(),
    updatedAt: new Date(),
  };
  