/**
 * QuestionerAdapter — Drizzle implementation of the QuestionerDatabase
 * contract from @indexnetwork/protocol.
 *
 * Persists structured questions generated by the QuestionerAgent and
 * exposes retrieval/mutation for the question lifecycle (pending → answered
 * or dismissed).
 *
 * Per adapter layering rules the local types are defined here; structural
 * alignment with protocol interfaces is verified by the compile-time
 * alignment spec.
 */

import { eq, and, sql, or, isNull, desc } from 'drizzle-orm/sql';

import { intents, questions, opportunities } from '../schemas/database.schema';
import type { QuestionDetection, QuestionActor } from '../schemas/database.schema';
import type { DrizzleDB } from '../lib/drizzle/drizzle';
import { QuestionEvents } from '../events/question.event';
import { normalizeIntentText } from '../lib/intent/intent.fingerprint';

/** Default question TTL in milliseconds (7 days). */
const DEFAULT_QUESTION_TTL_MS = 7 * 24 * 60 * 60 * 1000;

// ─── Local adapter types (structurally aligned with protocol contracts) ───────

/** Union of all question modes the adapter stores. */
export type AdapterQuestionMode = 'discovery' | 'intent' | 'enrichment' | 'negotiation' | 'negotiation_inflight' | 'chat' | 'pool_discovery';

/** Detection context describing how/where a question was generated. */
export interface AdapterQuestionDetection {
  mode: AdapterQuestionMode;
  sourceType: string;
  sourceId: string;
  triggeredBy?: string;
  timestamp: string;
  /** Generation strategy persisted as internal metadata. */
  strategy?: import('@indexnetwork/protocol').QuestionStrategy;
  /** QUD repair category persisted as internal metadata. */
  underspecificationType?: import('@indexnetwork/protocol').UnderspecificationType | null;
  /** ID of the assistant message that triggered this question. */
  messageId?: string;
  /**
   * pool_discovery only: mined pool snapshot (assignments + chain alternates).
   * INTERNAL — the service/controller read paths strip this before any
   * payload leaves the server.
   */
  pool?: import('@indexnetwork/protocol').QuestionPoolSnapshot;
}

/** An actor targeted by a question (typically the user who should answer). */
export interface AdapterQuestionActor {
  userId: string;
  networkId?: string;
  role: 'subject';
}

/** The user-facing question payload (title, prompt, options). */
export interface AdapterQuestionPayload {
  title: string;
  prompt: string;
  options: Array<{ label: string; description: string }>;
  multiSelect: boolean;
  /** Optional provenance chip line (e.g. "based on 18 people matching this intent"). */
  evidence?: string;
}

/** Answer recorded when a user responds to a question. */
export interface AdapterQuestionAnswer {
  selectedOptions: string[];
  freeText?: string;
  answeredBy: string;
  answeredAt: string;
}

/** Input shape for persisting a new question (no DB id or status yet). */
export interface AdapterPersistableQuestion {
  detection: AdapterQuestionDetection;
  actors: AdapterQuestionActor[];
  payload: AdapterQuestionPayload;
  strategy: import('@indexnetwork/protocol').QuestionStrategy;
  /** Internal QUD repair category; null when no underspecification is repaired. */
  underspecificationType?: import('@indexnetwork/protocol').UnderspecificationType | null;
  /** Conversation ID — set when the question originates from a chat session. */
  conversationId?: string;
}

/** A question row returned from the database. */
export interface AdapterPersistedQuestion {
  id: string;
  detection: AdapterQuestionDetection;
  actors: AdapterQuestionActor[];
  payload: AdapterQuestionPayload;
  status: 'pending' | 'answered' | 'dismissed';
  answer: AdapterQuestionAnswer | null;
  expiresAt: string | null;
  createdAt: string;
  conversationId: string | null;
}

/** Optional filters for the `findPending` query. */
export interface PoolQuestionFreshnessOptions {
  /** Fingerprint of the full current intent payload + summary. */
  currentIntentFingerprint?: string;
  /** Current intent text used for conservative legacy-prefix freshness. */
  currentIntentText?: string;
}

export interface AdapterQuestionFilters {
  mode?: AdapterQuestionMode;
  sourceType?: string;
  sourceId?: string;
  /**
   * Optional selected-intent scope. When `scopeType === 'intent'`, `scopeId` is the selected
   * intent id. Matches questions triggered by the intent, intent-mode questions about it, and
   * any question sourced from an opportunity linked to the intent (including negotiation
   * questions, since those persist with `sourceType: 'opportunity'`).
   */
  scopeType?: 'intent';
  scopeId?: string;
  /** Restrict to questions whose actor carries this network id. */
  networkId?: string;
  /** Filter to questions linked to a specific conversation. */
  conversationId?: string;
  /** When true, only return questions with no conversationId (sidebar-only). */
  noConversation?: boolean;
  /** Restrict to questions whose detection mode is in this set. */
  modes?: AdapterQuestionMode[];
  /**
   * Drop questions whose detection mode is in this set. Used by non-scoped
   * surfaces (global chat, questions inbox) to hide intent-scoped
   * pool_discovery questions until the P5 push channel ships (IND-418/421).
   */
  excludeModes?: AdapterQuestionMode[];
  /** Maximum rows to return (applied as a SQL LIMIT). */
  limit?: number;
}

/**
 * QuestionerAdapter — persists and queries the `questions` table.
 *
 * Accepts a Drizzle DB instance via constructor injection for testability.
 */
export class QuestionerAdapter {
  constructor(private readonly db: DrizzleDB) {}

  /**
   * Read the lifecycle fields needed to admit intent-scoped question work.
   *
   * @param intentId - Intent tied to the queued question job.
   * @param userId - Expected intent owner.
   * @returns Lifecycle row, or null for missing/foreign intents.
   */
  async getIntentLifecycle(intentId: string, userId: string): Promise<{
    id: string;
    status: 'ACTIVE' | 'PAUSED' | 'FULFILLED' | 'EXPIRED' | null;
    archivedAt: Date | null;
  } | null> {
    const rows = await this.db
      .select({ id: intents.id, status: intents.status, archivedAt: intents.archivedAt })
      .from(intents)
      .where(and(eq(intents.id, intentId), eq(intents.userId, userId)))
      .limit(1);
    return rows[0] ?? null;
  }

  /**
   * Persist a batch of generated questions.
   *
   * @param batch - Questions to insert (up to 3 per generation).
   * @returns The IDs of the inserted rows.
   */
  async persist(batch: AdapterPersistableQuestion[]): Promise<string[]> {
    if (batch.length === 0) return [];
    const rows = batch.map((q) => ({
      detection: {
        ...q.detection,
        strategy: q.strategy,
        underspecificationType: q.underspecificationType ?? null,
      } satisfies QuestionDetection,
      actors: q.actors as QuestionActor[],
      payload: q.payload,
      status: 'pending' as const,
      expiresAt: new Date(Date.now() + DEFAULT_QUESTION_TTL_MS),
      conversationId: q.conversationId ?? null,
    }));

    const inserted = await this.db.insert(questions).values(rows).returning({ id: questions.id });
    return inserted.map((r) => r.id);
  }

  /**
   * Find pending questions for a given user, optionally filtered by
   * detection mode, source type, source id, or selected-intent scope.
   *
   * Uses a jsonb containment query (`@>`) to locate rows where the
   * `actors` array includes an entry with the target userId.
   *
   * @param userId  - The user to find pending questions for.
   * @param filters - Optional narrowing filters (mode/modes, source, conversation, intent scope, SQL limit).
   * @returns Pending questions ordered by creation time (oldest first).
   */
  async findPending(
    userId: string,
    filters?: AdapterQuestionFilters,
  ): Promise<AdapterPersistedQuestion[]> {
    const actorMatch = filters?.networkId
      ? [{ userId, networkId: filters.networkId }]
      : [{ userId }];
    const conditions = [
      eq(questions.status, 'pending'),
      sql`${questions.actors}::jsonb @> ${JSON.stringify(actorMatch)}::jsonb`,
      or(isNull(questions.expiresAt), sql`${questions.expiresAt} > NOW()`),
    ];

    if (filters?.mode) {
      conditions.push(sql`${questions.detection}->>'mode' = ${filters.mode}`);
    }
    if (filters?.sourceType) {
      conditions.push(sql`${questions.detection}->>'sourceType' = ${filters.sourceType}`);
    }
    if (filters?.sourceId) {
      conditions.push(sql`${questions.detection}->>'sourceId' = ${filters.sourceId}`);
    }
    if (filters?.scopeType === 'intent' && filters.scopeId) {
      conditions.push(sql`(
        ${questions.detection}->>'triggeredBy' = ${filters.scopeId}
        OR (
          ${questions.detection}->>'mode' = 'intent'
          AND ${questions.detection}->>'sourceType' = 'intent'
          AND ${questions.detection}->>'sourceId' = ${filters.scopeId}
        )
        OR (
          ${questions.detection}->>'mode' = 'discovery'
          AND ${questions.detection}->>'sourceType' = 'discovery'
          AND ${questions.detection}->>'triggeredBy' = ${filters.scopeId}
        )
        OR (
          ${questions.detection}->>'sourceType' = 'opportunity'
          AND EXISTS (
            SELECT 1
            FROM ${opportunities} scoped_opp
            WHERE scoped_opp.id::text = ${questions.detection}->>'sourceId'
              AND (
                scoped_opp.detection->>'triggeredBy' = ${filters.scopeId}
                OR EXISTS (
                  SELECT 1
                  FROM jsonb_array_elements(scoped_opp.actors) AS actor
                  WHERE actor->>'intent' = ${filters.scopeId}
                )
              )
          )
        )
      )`);
    }
    if (filters?.conversationId) {
      conditions.push(eq(questions.conversationId, filters.conversationId));
    }
    if (filters?.noConversation) {
      conditions.push(isNull(questions.conversationId));
    }
    if (filters?.modes && filters.modes.length > 0) {
      const modeConditions = filters.modes.map(
        (mode) => sql`${questions.detection}->>'mode' = ${mode}`,
      );
      conditions.push(or(...modeConditions)!);
    }
    if (filters?.excludeModes && filters.excludeModes.length > 0) {
      for (const mode of filters.excludeModes) {
        conditions.push(sql`${questions.detection}->>'mode' <> ${mode}`);
      }
    }

    const baseQuery = this.db
      .select()
      .from(questions)
      .where(and(...conditions))
      .orderBy(questions.createdAt);

    const rows = filters?.limit && filters.limit > 0
      ? await baseQuery.limit(filters.limit)
      : await baseQuery;

    return rows.map(toPersistedQuestion);
  }

  /**
   * Discriminator labels used for exact dedup. Pending labels always count;
   * resolved labels count only while their intent snapshot is fresh when
   * freshness options are supplied. Omitting options preserves the legacy
   * any-status behavior.
   *
   * @param userId - Owner of the pool questions.
   * @param intentId - Intent tied to the questions.
   * @param freshness - Optional current-intent freshness context.
   * @returns Exact discriminator labels that should be deduplicated.
   */
  async listPoolQuestionLabels(
    userId: string,
    intentId: string,
    freshness?: PoolQuestionFreshnessOptions,
  ): Promise<string[]> {
    const rows = await this.db
      .select({
        status: questions.status,
        label: sql<string | null>`${questions.detection}->'pool'->'discriminator'->>'label'`,
        intentFingerprint: sql<string | null>`${questions.detection}->'pool'->>'intentFingerprint'`,
        intentText: sql<string | null>`${questions.detection}->'pool'->>'intentText'`,
      })
      .from(questions)
      .where(and(
        sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        sql`${questions.detection}->>'mode' = 'pool_discovery'`,
        sql`${questions.detection}->>'triggeredBy' = ${intentId}`,
      ));
    return rows.flatMap((row) => {
      const poolFreshness = {
        ...(row.intentFingerprint ? { intentFingerprint: row.intentFingerprint } : {}),
        ...(row.intentText ? { intentText: row.intentText } : {}),
      };
      if (!row.label || !isPoolQuestionFresh(row.status, poolFreshness, freshness)) return [];
      return [row.label];
    });
  }

  /**
   * Read fresh answered or dismissed axes for durable semantic novelty.
   * "Both matter" answers and dismissals intentionally remain references;
   * they resolve the axis even though they do not create a ranking preference.
   *
   * @param userId - Owner of the resolved questions.
   * @param intentId - Intent tied to the questions.
   * @param freshness - Current full-intent fingerprint and text.
   * @returns Fresh resolved discriminator snapshots, newest first.
   */
  async listResolvedPoolAxes(
    userId: string,
    intentId: string,
    freshness: PoolQuestionFreshnessOptions,
  ): Promise<import('@indexnetwork/protocol').QuestionPoolDiscriminator[]> {
    const storedFingerprint = sql<string | null>`${questions.detection}->'pool'->>'intentFingerprint'`;
    const storedIntentText = sql<string | null>`${questions.detection}->'pool'->>'intentText'`;
    const normalizedStoredIntentText = sql<string>`regexp_replace(btrim(normalize(COALESCE(${storedIntentText}, ''), NFKC)), '[[:space:]]+', ' ', 'g')`;
    const normalizedCurrentIntentText = freshness.currentIntentText
      ? normalizeIntentText(freshness.currentIntentText)
      : undefined;
    const freshnessPredicate = or(
      freshness.currentIntentFingerprint
        ? sql`${storedFingerprint} = ${freshness.currentIntentFingerprint}`
        : undefined,
      normalizedCurrentIntentText
        ? and(
            sql`${storedFingerprint} IS NULL`,
            sql`${storedIntentText} IS NOT NULL`,
            sql`(
              (char_length(${normalizedStoredIntentText}) < 160 AND ${normalizedStoredIntentText} = ${normalizedCurrentIntentText})
              OR
              (char_length(${normalizedStoredIntentText}) = 160 AND left(${normalizedCurrentIntentText}, 160) = ${normalizedStoredIntentText})
            )`,
          )
        : undefined,
    ) ?? sql`false`;

    const rows = await this.db
      .select({
        discriminator: sql<import('@indexnetwork/protocol').QuestionPoolDiscriminator | null>`${questions.detection}->'pool'->'discriminator'`,
      })
      .from(questions)
      .where(and(
        or(eq(questions.status, 'answered'), eq(questions.status, 'dismissed')),
        sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        sql`${questions.detection}->>'mode' = 'pool_discovery'`,
        sql`${questions.detection}->>'triggeredBy' = ${intentId}`,
        freshnessPredicate,
      ))
      .orderBy(desc(questions.createdAt))
      .limit(24);
    return rows.flatMap((row) => row.discriminator ? [row.discriminator] : []);
  }

  /**
   * Stamp an answered pool question with the post-refinement intent fingerprint.
   *
   * @param questionId - Answered pool question to update.
   * @param userId - Expected question actor.
   * @param intentFingerprint - Fingerprint computed from the applied update result.
   * @returns Whether the answered pool snapshot was updated.
   */
  async updateAnsweredPoolIntentFingerprint(
    questionId: string,
    userId: string,
    intentFingerprint: string,
  ): Promise<boolean> {
    const [updated] = await this.db
      .update(questions)
      .set({
        detection: sql`jsonb_set(${questions.detection}::jsonb, '{pool,intentFingerprint}', to_jsonb(${intentFingerprint}::text), true)`,
      })
      .where(and(
        eq(questions.id, questionId),
        eq(questions.status, 'answered'),
        sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        sql`${questions.detection}->>'mode' = 'pool_discovery'`,
        sql`${questions.detection}->'pool' IS NOT NULL`,
      ))
      .returning({ id: questions.id });
    return Boolean(updated);
  }

  /**
   * Read valid answered discriminator preferences for one intent. "Both
   * matter" and malformed answers are excluded because they intentionally do
   * not shape Tier-1 re-discovery (IND-419).
   *
   * @param userId - Owner of the answered questions.
   * @param intentId - Intent whose pool questions were answered.
   * @returns Latest valid side choices, newest first.
   */
  async listAnsweredPoolPreferences(
    userId: string,
    intentId: string,
  ): Promise<Array<{ questionId: string; label: string; chosenSide: string }>> {
    const rows = await this.db
      .select({
        id: questions.id,
        detection: questions.detection,
        answer: questions.answer,
      })
      .from(questions)
      .where(and(
        eq(questions.status, 'answered'),
        sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        sql`${questions.detection}->>'mode' = 'pool_discovery'`,
        sql`${questions.detection}->>'triggeredBy' = ${intentId}`,
      ))
      .orderBy(desc(questions.createdAt))
      .limit(10);

    return rows.flatMap((row) => {
      const detection = row.detection as AdapterQuestionDetection;
      const selected = (row.answer as AdapterQuestionAnswer | null)?.selectedOptions?.[0];
      const discriminator = detection.pool?.discriminator;
      if (!selected || !discriminator) return [];
      const chosenSide = discriminator.sides.find(
        (side) => side === selected || side.startsWith(selected) || selected.startsWith(side),
      );
      if (!chosenSide) return [];
      return [{ questionId: row.id, label: discriminator.label, chosenSide }];
    });
  }

  /**
   * Fetch a single question by id.
   *
   * @param questionId - ID of the question to fetch.
   * @returns The question row, or null when not found.
   */
  async getById(questionId: string): Promise<AdapterPersistedQuestion | null> {
    const [row] = await this.db
      .select()
      .from(questions)
      .where(eq(questions.id, questionId))
      .limit(1);

    return row ? toPersistedQuestion(row) : null;
  }

  /**
   * Record an answer for a question, setting its status to `answered`.
   * Emits `QuestionEvents.onAnswered` after persisting the answer.
   * Only updates the question if the user is listed as an actor.
   *
   * @param questionId - ID of the question to answer.
   * @param userId     - Authenticated user; must be an actor on the question.
   * @param answer     - The user's response data.
   * @returns `true` if a row was updated, `false` if no matching question found.
   */
  async answer(questionId: string, userId: string, answer: AdapterQuestionAnswer): Promise<boolean> {
    const [updated] = await this.db
      .update(questions)
      .set({ status: 'answered', answer })
      .where(
        and(
          eq(questions.id, questionId),
          eq(questions.status, 'pending'),
          sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        ),
      )
      .returning({ id: questions.id, detection: questions.detection });

    if (!updated) return false;

    const detection = updated.detection as AdapterQuestionDetection;
    QuestionEvents.onAnswered({
      questionId,
      userId,
      mode: detection.mode,
      sourceType: detection.sourceType,
      sourceId: detection.sourceId,
      answer,
    });

    return true;
  }

  /**
   * Dismiss a question, setting its status to `dismissed`.
   * Emits `QuestionEvents.onDismissed` after persisting (used to unblock chat
   * turns awaiting an ask_user_question answer).
   * Only updates the question if the user is listed as an actor.
   *
   * @param questionId - ID of the question to dismiss.
   * @param userId     - Authenticated user; must be an actor on the question.
   * @returns `true` if a row was updated, `false` if no matching question found.
   */
  async dismiss(questionId: string, userId: string): Promise<boolean> {
    const [updated] = await this.db
      .update(questions)
      .set({ status: 'dismissed' })
      .where(
        and(
          eq(questions.id, questionId),
          eq(questions.status, 'pending'),
          sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
        ),
      )
      .returning({ id: questions.id, detection: questions.detection });

    if (!updated) return false;

    const detection = updated.detection as AdapterQuestionDetection;
    QuestionEvents.onDismissed({
      questionId,
      userId,
      mode: detection.mode,
      sourceType: detection.sourceType,
      sourceId: detection.sourceId,
    });

    return true;
  }
}

// ─── Internal helpers ────────────────────────────────────────────────────────

/** Whether a pool snapshot still belongs to the current material intent. */
function isPoolQuestionFresh(
  status: AdapterPersistedQuestion['status'],
  pool: Pick<import('@indexnetwork/protocol').QuestionPoolSnapshot, 'intentFingerprint' | 'intentText'>,
  freshness?: PoolQuestionFreshnessOptions,
): boolean {
  if (!freshness || status === 'pending') return true;
  if (
    pool.intentFingerprint
    && freshness.currentIntentFingerprint
  ) {
    return pool.intentFingerprint === freshness.currentIntentFingerprint;
  }
  if (!pool.intentFingerprint && pool.intentText && freshness.currentIntentText) {
    const storedIntentText = normalizeIntentText(pool.intentText);
    const currentIntentText = normalizeIntentText(freshness.currentIntentText);
    if (storedIntentText.length < 160) return storedIntentText === currentIntentText;
    return storedIntentText.length === 160 && currentIntentText.startsWith(storedIntentText);
  }
  return false;
}

/** Map a raw Drizzle row into the adapter's persisted-question shape. */
function toPersistedQuestion(
  row: typeof questions.$inferSelect,
): AdapterPersistedQuestion {
  return {
    id: row.id,
    detection: row.detection as AdapterQuestionDetection,
    actors: row.actors as AdapterQuestionActor[],
    payload: row.payload as AdapterQuestionPayload,
    status: row.status,
    answer: (row.answer as AdapterQuestionAnswer) ?? null,
    expiresAt: row.expiresAt?.toISOString() ?? null,
    createdAt: row.createdAt.toISOString(),
    conversationId: row.conversationId ?? null,
  };
}
