#!/usr/bin/env bun
/**
 * Snapshots the only supported protocol entry point and generates the consumer
 * type-check fixture from it. Both outputs are intentionally checked in: a
 * barrel change must be reviewed as a public-contract change.
 */
import { readFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import ts from "typescript";

type Stability = "stable" | "experimental";
type ExportKind = "type" | "value";

type ExportInventoryEntry = {
  name: string;
  kind: ExportKind;
  stability: Stability;
  source: string;
};

type ExportInventory = {
  schemaVersion: 1;
  entryPoint: "src/index.ts";
  exports: ExportInventoryEntry[];
};

const packageRoot = resolve(dirname(new URL(import.meta.url).pathname), "../..");
const indexPath = resolve(packageRoot, "src/index.ts");
const snapshotPath = resolve(packageRoot, "architecture/exports.snapshot.json");
const fixturePath = resolve(packageRoot, "architecture/consumer/public-api.ts");

function sectionStability(leadingTrivia: string, current: Stability): Stability {
  if (/─{3,}/.test(leadingTrivia)) current = "stable";
  if (/(?:^|\n)\s*\/\/\s*@experimental\b/.test(leadingTrivia)) current = "experimental";
  return current;
}

function inventoryFrom(sourceText: string): ExportInventory {
  const sourceFile = ts.createSourceFile(indexPath, sourceText, ts.ScriptTarget.Latest, true);
  const entries: ExportInventoryEntry[] = [];
  let stability: Stability = "stable";
  let previousEnd = 0;

  for (const statement of sourceFile.statements) {
    stability = sectionStability(sourceText.slice(previousEnd, statement.getStart(sourceFile)), stability);
    previousEnd = statement.end;

    if (!ts.isExportDeclaration(statement) || !statement.exportClause || !ts.isNamedExports(statement.exportClause)) continue;
    const source = statement.moduleSpecifier && ts.isStringLiteral(statement.moduleSpecifier)
      ? statement.moduleSpecifier.text
      : "./index";

    for (const element of statement.exportClause.elements) {
      entries.push({
        name: element.name.text,
        kind: statement.isTypeOnly || element.isTypeOnly ? "type" : "value",
        stability,
        source,
      });
    }
  }

  const duplicate = entries.find((entry, index) => entries.findIndex((other) => other.name === entry.name) !== index);
  if (duplicate) throw new Error(`src/index.ts exports ${duplicate.name} more than once.`);

  return { schemaVersion: 1, entryPoint: "src/index.ts", exports: entries };
}

function consumerFixture(inventory: ExportInventory): string {
  const values = inventory.exports.filter((entry) => entry.kind === "value").map((entry) => entry.name);
  const types = inventory.exports.filter((entry) => entry.kind === "type").map((entry) => entry.name);
  const namedImport = (prefix: string, names: string[]) => [
    `${prefix}{`,
    ...names.map((name) => `  ${name},`),
    '} from "../../src/index.js";',
  ].join("\n");
  return [
    "// Generated by scripts/architecture/export-inventory.ts. Do not edit by hand.",
    "// This fixture makes every supported root export part of a consumer type-check.",
    "/* eslint-disable @typescript-eslint/no-unused-vars */",
    namedImport("import ", values),
    namedImport("import type ", types),
    "",
  ].join("\n");
}

const inventory = inventoryFrom(await readFile(indexPath, "utf8"));
const expectedSnapshot = JSON.stringify(inventory, null, 2) + "\n";
const expectedFixture = consumerFixture(inventory);
const write = process.argv.includes("--write");

if (write) {
  await Bun.write(snapshotPath, expectedSnapshot);
  await Bun.write(fixturePath, expectedFixture);
  console.log(`Updated ${inventory.exports.length} root exports and the consumer fixture.`);
  process.exit(0);
}

const [actualSnapshot, actualFixture] = await Promise.all([
  Bun.file(snapshotPath).text(),
  Bun.file(fixturePath).text(),
]);
if (actualSnapshot !== expectedSnapshot || actualFixture !== expectedFixture) {
  throw new Error("Protocol public API inventory changed. Review it, then run: bun run architecture:exports:update");
}

const stable = inventory.exports.filter((entry) => entry.stability === "stable").length;
const experimental = inventory.exports.length - stable;
console.log(`Export inventory OK (${inventory.exports.length} exports: ${stable} stable, ${experimental} experimental).`);
