/**
 * Protocol-level persistence contract for structured questions generated by
 * the QuestionerAgent. Implementations live in the backend and are injected
 * into ProtocolDeps.
 */
import type {
  Question,
  QuestionMode,
  QuestionStrategy,
  QuestionDetection,
  QuestionActor,
  QuestionAnswer,
} from "../schemas/question.schema.js";

/** Shape accepted by `persist()` — everything needed to insert a question row. */
export interface PersistableQuestion {
  detection: QuestionDetection;
  actors: QuestionActor[];
  payload: Question;
  strategy: QuestionStrategy;
}

/** Shape returned by `findPending()` — a persisted question with its DB id and status. */
export interface PersistedQuestion {
  id: string;
  detection: QuestionDetection;
  actors: QuestionActor[];
  payload: Question;
  status: "pending" | "answered" | "dismissed";
  answer: QuestionAnswer | null;
  createdAt: string;
}

/** Optional filters for `findPending()`. */
export interface QuestionFilters {
  mode?: QuestionMode;
  sourceType?: string;
  sourceId?: string;
}

export interface QuestionerDatabase {
  /** Persist a batch of generated questions (up to 3 per generation). */
  persist(questions: PersistableQuestion[]): Promise<void>;

  /** Find pending questions for a user, optionally filtered by mode/source. */
  findPending(userId: string, filters?: QuestionFilters): Promise<PersistedQuestion[]>;

  /** Record an answer for a question. Sets status to "answered". */
  answer(questionId: string, answer: QuestionAnswer): Promise<void>;

  /** Dismiss a question. Sets status to "dismissed". */
  dismiss(questionId: string): Promise<void>;
}
