#!/usr/bin/env node
/**
 * Generate plugin.js — the Hermes DESKTOP app plugin — from the shared
 * dashboard bundle, so both hosts render the same UI from one source:
 *
 *   head.js + ../dashboard/dist/index.js + notifications.mjs + tail.js
 *   (SDK wiring, dashboard, pure notification helpers, registration; CSS inlined)
 *
 * Run after any dashboard change:  node packages/hermes-plugin/desktop/build.mjs
 * Hermes installs this file from desktop/plugin.js. Do not copy it into
 * desktop-plugins yourself.
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = p => readFileSync(join(here, p), 'utf8')

// The stylesheet points at dashboard/fonts/. This host injects the sheet as a
// <style> with no base URL, so those file urls are inlined here.
const css = (read('theme-map.css') + '\n' + read('../dashboard/dist/style.css')).replace(
  /url\(\.\.\/fonts\/([^)]+)\)/g,
  (_, file) => {
    const bytes = readFileSync(join(here, '../dashboard/fonts', file))
    return `url(data:font/woff2;base64,${bytes.toString('base64')})`
  }
)
const tail = read('tail.js').replace('__PLUGIN_CSS__', () => JSON.stringify(css))

const out = [
  '// GENERATED by desktop/build.mjs — do not edit. Sources: desktop/head.js,',
  '// dashboard/dist/index.js, desktop/notifications.mjs, desktop/tail.js',
  '// (+ theme-map.css, style.css).',
  read('head.js'),
  read('../dashboard/dist/index.js'),
  read('notifications.mjs'),
  tail
  // Defensive statement separator: a fragment ending without `;` must not
  // swallow the next fragment's leading `(` (ASI would parse it as a call).
].join('\n;\n')

writeFileSync(join(here, 'plugin.js'), out)
console.log(`wrote desktop/plugin.js (${(out.length / 1024).toFixed(0)} KB)`)
