#!/usr/bin/env node
/**
 * Generate dist/plugin.js — the Hermes DESKTOP app plugin — from the shared
 * dashboard bundle, so both hosts render the same UI from one source:
 *
 *   head.js  (SDK wiring)  +  ../dashboard/dist/index.js  +  tail.js
 *   (registration; theme-map.css + ../dashboard/dist/style.css inlined)
 *
 * Run after any dashboard change:  node packages/hermes-plugin/desktop/build.mjs
 * Install: ln -s .../packages/hermes-plugin/desktop/dist ~/.hermes/desktop-plugins/index-network
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const read = p => readFileSync(join(here, p), 'utf8')

const css = read('theme-map.css') + '\n' + read('../dashboard/dist/style.css')
const tail = read('tail.js').replace('__PLUGIN_CSS__', () => JSON.stringify(css))

const out = [
  '// GENERATED by desktop/build.mjs — do not edit. Sources: desktop/head.js,',
  '// dashboard/dist/index.js, desktop/tail.js (+ theme-map.css, style.css).',
  read('head.js'),
  read('../dashboard/dist/index.js'),
  tail
  // Defensive statement separator: a fragment ending without `;` must not
  // swallow the next fragment's leading `(` (ASI would parse it as a call).
].join('\n;\n')

mkdirSync(join(here, 'dist'), { recursive: true })
writeFileSync(join(here, 'dist/plugin.js'), out)
console.log(`wrote desktop/dist/plugin.js (${(out.length / 1024).toFixed(0)} KB)`)
