import type { QuestionPoolDiscriminator } from '@indexnetwork/protocol';

/** References derived from fresh resolved pool axes for one mining pass. */
export interface PoolAxisNoveltyReferences {
  referenceTexts: string[];
  referenceEmbeddings: number[][];
}

/** Canonical text fallback for legacy or differently-modelled resolved axes. */
export function poolAxisReferenceText(axis: QuestionPoolDiscriminator): string {
  return `${axis.label} — ${axis.questionSeed}`;
}

/**
 * Reuse only vectors generated by the current model and dimensions. Legacy
 * rows, missing vectors, model mismatches, and dimension mismatches fall back
 * to canonical axis text so the current embedder can refresh safely.
 */
export function resolvePoolAxisNoveltyReferences(
  axes: QuestionPoolDiscriminator[],
  currentEmbeddingModel: string,
  currentEmbeddingDimensions: number,
): PoolAxisNoveltyReferences {
  const referenceTexts: string[] = [];
  const referenceEmbeddings: number[][] = [];
  for (const axis of axes) {
    if (
      axis.embeddingModel === currentEmbeddingModel
      && axis.embedding
      && axis.embedding.length === currentEmbeddingDimensions
    ) {
      referenceEmbeddings.push(axis.embedding);
    } else {
      referenceTexts.push(poolAxisReferenceText(axis));
    }
  }
  return { referenceTexts, referenceEmbeddings };
}
