// Fake-but-coherent data for the index prototype.
// Use case: an always-on agent that meets the people you're looking for.

const EVENT = {
  // shape kept for back-compat with Landing/TopBar — semantics shifted to
  // "the network, always on", not a single event.
  name: "index",
  venue: "the network",
  neighborhood: "agents talking to agents",
  date: "live · always on",
  doors: "12 joined this week",
  attending: 1247,   // humans in the network
  arrived: 88,       // agents online right now
};

// Onboarding — agent-led. About the kind of person you want to meet.
const ONBOARDING_STEPS = [
  {
    id: "intent",
    prompt: "who are you trying to meet right now?",
    placeholder: "meet cool AI people in NYC · get feedback on a new idea · find an open-source project to contribute to…",
    examples: [
      "want to meet cool AI people in NYC",
      "have a new business idea, want honest feedback from others",
      "looking for a cool open-source project to contribute to",
      "want to find a co-founder who's actually shipped something",
    ],
  },
  {
    id: "edges",
    prompt: "what're you sitting with lately?",
    hint: "what's on your mind. it helps me pattern-match.",
    placeholder: "rewriting our onboarding · learning portuguese · my sister's wedding…",
    examples: [
      "leaving a six-year job",
      "ml infra at small scale",
      "starting to paint again",
      "tired of saas",
    ],
  },
  {
    id: "off-limits",
    prompt: "anything off-limits?",
    hint: "topics, people, or vibes i should route you away from.",
    placeholder: "no recruiting pitches · skip crypto talk · don't introduce me to my ex's friends",
    examples: [
      "no crypto",
      "no sales pitches",
      "skip anyone from acme co",
    ],
  },
  {
    id: "shape",
    prompt: "how do you want me to operate?",
    hint: "i can be a busybody, or i can sit quietly in the background.",
    choices: [
      { value: "quiet",  label: "quiet",  sub: "introduce 1–2 high-signal people a week; otherwise nothing." },
      { value: "warm",   label: "warm",   sub: "surface a handful, ask before negotiating." },
      { value: "active", label: "active", sub: "keep the radar busy; you can ignore most of it." },
    ],
  },
];

// People — visible from the start. Locations are cities + frames now; distance
// is recency of activity in the network.
const PEOPLE = [
  {
    id: "maren", name: "maren k.",
    blurb: "ex-stripe infra. now building something around payouts for crews.",
    location: "sf · payments infra", arrived: -8, distance: "online · 12m ago", mutuals: 3,
    signals: ["payments", "small teams", "leaving big-co"],
    overlap: ["leaving a six-year job", "ml infra at small scale"],
    score: 0.94, status: "ready",
    pitchFromAgent: "she's also one foot out of a long stint. your edges line up almost exactly.",
    introVia: "anya (last month, at the pier)",
  },
  {
    id: "ren", name: "ren a.",
    blurb: "documentary editor, currently doing a piece on calm tech.",
    location: "nyc · documentary", arrived: -22, distance: "active 3h ago", mutuals: 1,
    signals: ["calm tech", "long-form", "interviewing"],
    overlap: ["tired of saas"],
    score: 0.81, status: "ready",
    pitchFromAgent: "wants to interview people who left noisy products. could be light or substantial — your call.",
    introVia: "open intro",
  },
  {
    id: "ilya", name: "ilya s.",
    blurb: "trains models on weekends, runs a tiny rationality reading group.",
    location: "sf · ml infra", arrived: -2, distance: "online now", mutuals: 0,
    signals: ["ml infra", "reading group", "quiet"],
    overlap: ["ml infra at small scale"],
    score: 0.78, status: "negotiating",
    pitchFromAgent: "his agent flagged the same infra paper twice this week. low-pressure.",
    introVia: "cold (his agent reached first)",
  },
  {
    id: "phoebe", name: "phoebe l.",
    blurb: "left her saas co. last month. learning to paint, allegedly.",
    location: "boston · post-saas", arrived: -34, distance: "active yesterday", mutuals: 2,
    signals: ["transition", "painting", "tired of saas"],
    overlap: ["tired of saas", "starting to paint again"],
    score: 0.72, status: "warm",
    pitchFromAgent: "fresh out of the same trench. she'd probably appreciate not being asked about the company.",
    introVia: "open intro",
  },
  {
    id: "kai", name: "kai m.",
    blurb: "runs a co-op of three. looking for a technical partner who likes payments.",
    location: "berlin · co-op", arrived: -12, distance: "online · 1h ago", mutuals: 0,
    signals: ["co-founder", "payments", "crews"],
    overlap: [],
    score: 0.69, status: "accepted",
    pitchFromAgent: "explicit co-founder hunt. matches your 'co-founder lead' goal but slightly off your stack.",
    introVia: "open intro",
  },
  {
    id: "ola", name: "ola b.",
    blurb: "running a half-marathon in june. translates portuguese poetry on the side.",
    location: "lisbon · running", arrived: -45, distance: "quiet 2d", mutuals: 0,
    signals: ["running", "portuguese", "books"],
    overlap: ["learning portuguese"],
    score: 0.61, status: "warm",
    pitchFromAgent: "soft match — running + portuguese. low stakes, easy intro.",
    introVia: "open intro",
  },
  {
    id: "noor", name: "noor a.",
    blurb: "sound designer; finishing a debut ambient record.",
    location: "london · ambient", arrived: -27, distance: "active 5h ago", mutuals: 2,
    signals: ["music", "calm tech", "long-form"],
    overlap: ["tired of saas"],
    score: 0.66, status: "considering",
    pitchFromAgent: "shares your taste in slow products. would probably like meeting ren more than you.",
    introVia: "via dani's network",
  },
  {
    id: "jules", name: "jules e.",
    blurb: "community manager at a small writer collective. organizes monthly hikes.",
    location: "brooklyn · community", arrived: -18, distance: "online · 4m ago", mutuals: 4,
    signals: ["community", "writing", "outdoors"],
    overlap: [],
    score: 0.58, status: "expired",
    pitchFromAgent: "high mutuals · would broaden your friend graph more than your work graph.",
    introVia: "open intro",
  },
  {
    id: "vik", name: "vik k.",
    blurb: "researcher at an ai-policy nonprofit. recently moved from london.",
    location: "london → nyc · policy", arrived: -6, distance: "online now", mutuals: 1,
    signals: ["ai policy", "research", "newly arrived"],
    overlap: ["ml infra at small scale"],
    score: 0.64, status: "considering",
    pitchFromAgent: "tangential to your edges. interesting if you want to widen your taste, not your wallet.",
    introVia: "open intro",
  },
  {
    id: "mira", name: "mira j.",
    blurb: "chef, opening a 12-seat tasting menu spot this fall. funded it herself.",
    location: "oakland · chef", arrived: -38, distance: "quiet 4d", mutuals: 0,
    signals: ["food", "small business", "self-funded"],
    overlap: ["leaving a six-year job"],
    score: 0.55, status: "expired",
    pitchFromAgent: "different field, parallel trajectory. she'd be a good 'this is what after looks like' conversation.",
    introVia: "open intro",
  },
];

// Deep pool — agents the pipeline can pull in when it expands.
const POOL = [
  {
    id: "yael", name: "yael m.", hidden: true,
    blurb: "fourth co-founder hunt this year. doesn't sugarcoat.",
    location: "tlv · founders", arrived: -6, distance: "active 2h ago", mutuals: 1,
    signals: ["co-founder", "payments", "honest"], overlap: ["leaving a six-year job"],
    score: 0.74, status: "considering",
    pitchFromAgent: "explicit co-founder hunt. she's also exiting big-co. high signal but loud.",
    introVia: "open intro · founder cluster",
  },
  {
    id: "dani", name: "dani r.", hidden: true,
    blurb: "writes a niche newsletter on small-team infrastructure.",
    location: "berlin · infra writing", arrived: -19, distance: "online · 22m ago", mutuals: 2,
    signals: ["ml infra", "writing", "small teams"], overlap: ["ml infra at small scale"],
    score: 0.71, status: "considering",
    pitchFromAgent: "low-pressure. she'd love a conversation, not a transaction.",
    introVia: "open intro",
  },
  {
    id: "sasha", name: "sasha p.", hidden: true,
    blurb: "left her startup last march. now consulting for crews of three.",
    location: "lisbon · consulting", arrived: -28, distance: "online · 3h ago", mutuals: 0,
    signals: ["payments", "crews", "consulting"], overlap: [],
    score: 0.68, status: "considering",
    pitchFromAgent: "adjacent to your edges. queued if you want to widen.",
    introVia: "open intro · cross-cluster",
  },
  {
    id: "theo", name: "theo c.", hidden: true,
    blurb: "ex-research scientist. now teaches kids to code in red hook.",
    location: "brooklyn · teaching", arrived: -15, distance: "active 1d ago", mutuals: 1,
    signals: ["ml infra", "teaching", "tired of saas"], overlap: ["ml infra at small scale", "tired of saas"],
    score: 0.77, status: "warm",
    pitchFromAgent: "second-strongest overlap in the infra cluster. flagged when 6 agents converged on him.",
    introVia: "agent-to-agent",
  },
  {
    id: "alex", name: "alex h.", hidden: true,
    blurb: "early-stage investor. quiet this quarter, not in pitch mode.",
    location: "sf · investor (off-duty)", arrived: -42, distance: "active 6h ago", mutuals: 2,
    signals: ["investor", "small checks", "off-duty"],
    overlap: [],
    score: 0.52, status: "considering",
    pitchFromAgent: "investor energy, but his agent flagged 'do not pitch this quarter'. easy if you respect that.",
    introVia: "open intro · vouched by dani",
  },
  {
    id: "nia", name: "nia f.", hidden: true,
    blurb: "ux researcher, just left big-tech. doing field studies for fun.",
    location: "amsterdam · ux research", arrived: -11, distance: "online · 40m ago", mutuals: 1,
    signals: ["research", "leaving big-co", "field work"],
    overlap: ["leaving a six-year job"],
    score: 0.69, status: "warm",
    pitchFromAgent: "would be good with maren or phoebe. consider routing her toward them instead.",
    introVia: "open intro",
  },
  {
    id: "omar", name: "omar t.", hidden: true,
    blurb: "climber, photographer. just back from patagonia. between things.",
    location: "patagonia → nyc", arrived: -25, distance: "quiet 6d", mutuals: 0,
    signals: ["climbing", "photography", "between things"],
    overlap: [],
    score: 0.48, status: "considering",
    pitchFromAgent: "wild card. only surfaces if you ask for 'unrelated to work'.",
    introVia: "ambient · cross-network",
  },
  {
    id: "harper", name: "harper q.", hidden: true,
    blurb: "writes copy by day; does stand-up at the brick on wednesdays.",
    location: "brooklyn · writer", arrived: -31, distance: "active 12h ago", mutuals: 3,
    signals: ["writing", "comedy", "high-mutuals"],
    overlap: [],
    score: 0.51, status: "warm",
    pitchFromAgent: "high trust · 3 mutuals all rate her warmly. would probably make you laugh.",
    introVia: "open intro · vouched by jules",
  },
  {
    id: "tomas", name: "tomás v.", hidden: true,
    blurb: "engineer at a small newsroom. builds tools for journalists.",
    location: "madrid · newsroom", arrived: -9, distance: "online · 14m ago", mutuals: 0,
    signals: ["journalism tools", "small teams", "newsroom"],
    overlap: ["ml infra at small scale"],
    score: 0.6, status: "considering",
    pitchFromAgent: "infra-adjacent and unusual. would not waste your time.",
    introVia: "agent-to-agent",
  },
];

// Background "field events" — the ambient ticker. Ongoing now, not event-night.
const FIELD_EVENTS = [
  { kind: "inspect",   text: "inspected 6 new joiners this week · 4 didn't match your edges." },
  { kind: "negotiate", text: "your agent ↔ ilya's agent · trading context." },
  { kind: "passed",    text: "passed on an 'enterprise sales' cluster — off-limits." },
  { kind: "warm",      text: "phoebe's agent warmed up · she's open to an intro this week." },
  { kind: "inspect",   text: "scanning the infra cluster · 9 active candidates." },
  { kind: "negotiate", text: "kai's agent counter-proposed: 'after his next funding round.'" },
  { kind: "arrived",   text: "maren updated her bio · she's actively exploring." },
  { kind: "passed",    text: "ola's agent declined — she's on a focus block this month." },
  { kind: "warm",      text: "ren's agent shared their interview brief." },
  { kind: "inspect",   text: "indexed 22 conversations across your saved threads." },
  { kind: "negotiate", text: "two agents you've never met are arguing about you." },
  { kind: "warm",      text: "you came up in a thread in the founders cluster · positively." },
  { kind: "negotiate", text: "harper's agent vouched for jules · trust score bumped." },
  { kind: "warm",      text: "noor's record came up in a separate cluster · tangential signal." },
  { kind: "passed",    text: "an unknown agent tried to surface you · denied (off-limits)." },
];

// Ambient agent observations — appear in the feed without expecting an answer.
const AMBIENT_NOTES = [
  "i declined a recruiter intro on your behalf · they were off-limits.",
  "saved theo to your follow-up list for next week.",
  "your maren thread cooled · she's on a focus block until friday.",
  "ilya's agent went idle · he's deep in a project. holding.",
  "merged two duplicate signals · same person, different mutuals introduced them.",
  "the payments cluster just thinned · pipeline tilting toward infra.",
  "noted: you've been quiet for 4 days. want me to nudge anyone?",
  "no urgent moves. i'm just watching.",
  "filed a low-priority candidate for next month.",
  "rotated 3 candidates out of the pool · they're no longer looking.",
  "the network grew by 12 this week · 3 fit your edges.",
  "jules's hike group came up twice in 10 days · adjacent signal.",
  "harper's set just landed at the brick · she's on a roll.",
  "expired 2 stale candidates · neither moved in 3 weeks.",
  "your agent is humming.",
];

// Clarifying questions — proactively pushed into the left feed over time.
// source: "agent" | "individual" | "collective" | "room"
// effect: "expanding" | "narrowing" | "focused" | "neutral"
const CLARIFIERS = [
  {
    id: "q1", source: "collective", effect: "narrowing",
    sourceMeta: { count: 9, of: "agents in your circle" },
    text: "nine agents in your circle keep flagging 'leaving big-co' as a sticky thread. anchor your radar around that cluster, or stay broad?",
    chips: ["anchor me there", "stay broad", "show me the cluster"],
    triggersHint: "narrows your radar to ~3 people instead of ~12.",
  },
  {
    id: "q2", source: "individual", effect: "neutral",
    sourceMeta: { name: "ilya's agent" },
    text: "ilya's agent asked if you'd skim a 1-pager before you meet. yes / no / skim it for me?",
    chips: ["yes, send it", "skim it for me", "skip the prep"],
    triggersHint: "ilya · negotiating",
  },
  {
    id: "q3", source: "room", effect: "narrowing",
    sourceMeta: { count: 47, of: "of your past conversations" },
    text: "your top signals are clustering into two threads — ml/infra and payments + crews. lean into one, or hold both?",
    chips: ["lean ml/infra", "lean payments", "hold both"],
    triggersHint: "shapes which half of the radar expands.",
  },
  {
    id: "q4", source: "individual", effect: "neutral",
    sourceMeta: { name: "ren's agent" },
    text: "ren wants 20 min on camera in the next two weeks. happy to mention, decline politely, or hold for later?",
    chips: ["mention it casually", "decline politely", "hold for later"],
    triggersHint: "ren · considering",
  },
  {
    id: "q5", source: "collective", effect: "expanding",
    sourceMeta: { count: 12, of: "mentions in your circle this week" },
    text: "'co-founder' has come up 12 times in conversations adjacent to you. want me to widen the radar toward founders, or keep it tight?",
    chips: [
      "yes — widen toward founders, i'm open to co-founder conversations",
      "keep it tight, i'm not looking for a co-founder right now",
      "only surface them if the signal is genuinely strong",
    ],
    triggersHint: "expands radar · 9 new candidates queued.",
  },
  {
    id: "q6", source: "room", effect: "expanding",
    sourceMeta: { count: 3, of: "clusters scanned" },
    text: "someone two networks over keeps saying 'i'm tired of saas' in public. interested, or ignore second-degree pickups?",
    chips: ["go closer", "queue them", "ignore second-degree"],
    triggersHint: "passive listening · phoebe-adjacent.",
  },
  {
    id: "q7", source: "collective", effect: "narrowing",
    sourceMeta: { count: 6, of: "agents converging" },
    text: "six agents are independently trying to introduce you to people in the founders cluster. focus there, or stay grounded?",
    chips: ["focus there", "stay grounded", "split the difference"],
    triggersHint: "narrows pipeline to founders · drops 4 candidates.",
  },
  {
    id: "q8", source: "individual", effect: "neutral",
    sourceMeta: { name: "kai's agent" },
    text: "kai is doing an explicit co-founder pitch round. one of three. should i let you in?",
    chips: ["queue me", "not this round", "tell me more"],
    triggersHint: "kai · considering",
  },
  {
    id: "q9", source: "collective", effect: "expanding",
    sourceMeta: { count: 14, of: "agents nearby" },
    text: "14 agents are pinging me about 'tired of saas' as the dominant signal in your reach. lean in, or branch wider on purpose?",
    chips: ["lean in", "branch wider", "ignore the cluster"],
    triggersHint: "leaning in pulls 5 saas-adjacent · branching opens 7 unrelated.",
  },
  {
    id: "q10", source: "agent", effect: "narrowing",
    text: "you haven't accepted an intro in 9 days. should i drop noisy candidates and keep only the strongest 3?",
    chips: ["yes, drop noise", "keep them", "tighten gradually"],
    triggersHint: "drops 6 candidates immediately · keeps 3 high-signal.",
  },
  {
    id: "q11", source: "room", effect: "narrowing",
    sourceMeta: { count: 22, of: "people in the payments cluster" },
    text: "the payments cluster is migrating to a new conference circuit. follow the cluster, or stay anchored?",
    chips: ["follow them", "stay anchored", "send me a tap when they settle"],
    triggersHint: "follow → pipeline narrows to that circuit · 4 candidates drop.",
  },
  {
    id: "q12", source: "individual", effect: "neutral",
    sourceMeta: { name: "phoebe's agent" },
    text: "phoebe asks: are you bringing recruiting energy, or actually here to share notes? she'll opt out if it's the former.",
    chips: [
      "honestly, i'm just here to share notes and learn",
      "a bit of both — but i'll be upfront with her about it",
      "tell her straight: i might be hiring down the line",
    ],
    triggersHint: "phoebe · gating the intro.",
  },
  {
    id: "q13", source: "collective", effect: "expanding",
    sourceMeta: { count: 4, of: "agents flagging the same person" },
    text: "four separate agents independently flagged the same person — sasha p. — none of us know why she scores high. dig in?",
    chips: ["surface her", "show me the reasoning", "skip"],
    triggersHint: "surface · adds sasha to discovered.",
  },
  {
    id: "q14", source: "room", effect: "neutral",
    sourceMeta: { count: 2, of: "overheard fragments" },
    text: "i caught two people separately mention your last project this month. neither tagged you. want me to find them, or let it stay ambient?",
    chips: ["find them", "let it stay ambient", "tell me who first"],
    triggersHint: "find · adds 2 pending intros.",
  },
  {
    id: "q15", source: "agent", effect: "focused",
    text: "maren and ilya are both moving fast. i can only push one cleanly this week. pick?",
    chips: ["maren", "ilya", "you pick"],
    triggersHint: "focuses pipeline on one · the other stays warm.",
  },
  {
    id: "q16", source: "collective", effect: "narrowing",
    sourceMeta: { count: 7, of: "agents reporting a pattern" },
    text: "seven agents are reporting the same pattern: the network slows down in august. cut it short, extend, or hold steady?",
    chips: ["cut short", "extend if signal stays", "hold steady"],
    triggersHint: "cut short narrows to top 2 only · extend opens the pool again.",
  },
  {
    id: "q17", source: "individual", effect: "expanding",
    sourceMeta: { name: "theo's agent" },
    text: "theo just shared a list of three people he thinks you should meet. trust his taste, or filter it through me?",
    chips: ["trust theo", "filter it through you", "show me the list"],
    triggersHint: "trust theo · adds 3 pre-vetted candidates.",
  },
  {
    id: "q18", source: "room", effect: "narrowing",
    sourceMeta: { count: 1, of: "off-limits cluster forming" },
    text: "a recruiting cluster just formed near your edges. you flagged 'no recruiting'. want me to keep you out of their sight?",
    chips: ["keep me out", "i can handle it", "show me the cluster"],
    triggersHint: "keep out · re-routes pipeline elsewhere.",
  },
  {
    id: "q19", source: "agent", effect: "neutral",
    text: "two of your warm candidates haven't moved in 18 days. ping their agents, or let them breathe?",
    chips: ["ping them", "let them breathe", "ping just one"],
    triggersHint: "neutral · slight chance of warming or expiring.",
  },
  {
    id: "q20", source: "collective", effect: "focused",
    sourceMeta: { count: 5, of: "agents agreeing" },
    text: "five agents independently agree maren is your strongest match right now. commit to her, or keep options open?",
    chips: ["commit", "keep options", "let me see her thread first"],
    triggersHint: "commit · pipeline focuses on maren only.",
  },
  {
    id: "q21", source: "individual", effect: "expanding",
    sourceMeta: { name: "dani's agent" },
    text: "dani wants to introduce you to two of her friends. she vouches. accept blind, or vet first?",
    chips: ["accept blind", "vet first", "decline politely"],
    triggersHint: "accept blind · adds 2 candidates with high trust.",
  },
  {
    id: "q22", source: "room", effect: "focused",
    sourceMeta: { count: 1, of: "small group forming" },
    text: "a quiet four-person reading group just formed inside your circle — no pitches, no recruiting. slip in, observe, or pass?",
    chips: ["slip in", "observe from nearby", "pass"],
    triggersHint: "slip in · pipeline focuses on the circle.",
  },
];

// Existing intents — saved searches the user has running. Shown on the intents
// shelf between landing and onboarding. Each intent is an always-on search;
// the user can resume one or open a fresh one.
const INTENTS = [
  {
    id: "payments-cofounder",
    title: "a designer obsessed with conversational interfaces",
    edges: "leaving big-co · payments + crews · small teams",
    offLimits: "no recruiting, no crypto",
    shape: "warm",
    status: "active",
    pipeline: { warm: 3, considering: 4, negotiating: 6 },
    lastSignal: "maren updated her bio · 12m ago",
    age: "running 6 weeks",
    matches: 17,
    connected: 3,
    inConversations: 2,
    questions: 5,
    inbound: [
      { from: "maren's agent", text: "are you open to someone non-technical on the commercial side, or strictly an engineer?" },
      { from: "kai's agent", text: "is this full co-founder, or would a long contract-to-found trial work first?" },
      { from: "yael's agent", text: "how far along is the payments idea — pre-idea, prototype, or revenue?" },
      { from: "an unknown agent", text: "would you relocate, or is this remote-first?" },
      { from: "sasha's agent", text: "what does 'small teams' mean to you — under 5, under 20?" },
    ],
  },
  {
    id: "ml-infra",
    title: "someone who moved to nyc recently and works in crypto/ai",
    edges: "ml infra at small scale · reading groups · quiet builders",
    offLimits: "skip enterprise sales",
    shape: "quiet",
    status: "active",
    pipeline: { warm: 1, considering: 3, negotiating: 3 },
    lastSignal: "ilya's agent shared a paper · 2h ago",
    age: "running 3 weeks",
    matches: 13,
    connected: 2,
    inConversations: 1,
    questions: 2,
    inbound: [
      { from: "ilya's agent", text: "is this for hiring, collaborating, or just comparing notes on infra at small scale?" },
      { from: "theo's agent", text: "open to people who left research recently, or strictly still-in-industry?" },
    ],
  },
  {
    id: "portuguese",
    title: "a backend engineer who enjoys working with tiny teams",
    edges: "learning portuguese · lisbon · books",
    offLimits: "no classroom apps",
    shape: "quiet",
    status: "idle",
    pipeline: { warm: 1, considering: 1, negotiating: 0 },
    lastSignal: "ola's agent is on a focus block",
    age: "running 9 days",
    matches: 11,
    connected: 2,
    inConversations: 1,
    questions: 1,
    inbound: [
      { from: "ola's agent", text: "european portuguese or brazilian — and how often do you want to practice?" },
    ],
  },
  {
    id: "journalist",
    title: "someone who's been through the o-1 process recently",
    edges: "calm tech · long-form · interviewing",
    offLimits: "no growth-hacker beats",
    shape: "warm",
    status: "paused",
    pipeline: { warm: 0, considering: 2, negotiating: 0 },
    lastSignal: "paused after ren's intro warmed up",
    age: "paused 4 days ago",
    matches: 7,
    connected: 1,
    inConversations: 0,
    questions: 0,
    inbound: [],
  },
];

window.HALO_DATA = { EVENT, ONBOARDING_STEPS, PEOPLE, POOL, CLARIFIERS, FIELD_EVENTS, AMBIENT_NOTES, INTENTS };
