import { expect, test } from "bun:test";
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
const repo=resolve(import.meta.dir,"../../../.."), rel=resolve(import.meta.dir,".."), dmg=join(rel,"notarize-dmg.sh"), orchestrator=resolve(repo,"apps/mac/IndexApp/notarize.sh");
function run(s,e={}){return Bun.spawnSync(["bash","-c",s],{cwd:repo,env:{...process.env,...e},stdout:"pipe",stderr:"pipe"})}
test("standalone notarize-dmg always refuses, even for forged private directory, before codesign",()=>{const r=mkdtempSync(join(tmpdir(),"forged-")),d=join(r,".index-final-transaction.forged");mkdirSync(d,{mode:0o700});const f=join(d,"Index-macOS-1.0.0-universal.dmg"),bin=join(r,"bin"),log=join(r,"log");mkdirSync(bin);writeFileSync(f,"x");writeFileSync(join(bin,"codesign"),'#!/bin/bash\necho called >"$LOG"\n');chmodSync(join(bin,"codesign"),0o755);const x=Bun.spawnSync(["bash",dmg,f],{cwd:repo,env:{...process.env,LOG:log,PATH:`${bin}:${process.env.PATH}`},stdout:"pipe",stderr:"pipe"});expect(x.exitCode).not.toBe(0);expect(x.stderr.toString()).toContain("standalone execution is forbidden");expect(Bun.file(log).size).toBe(0)});
test("orchestrator sources DMG implementation in process and binds local readonly path plus inode device",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain('source "$RELEASE_DIRECTORY/notarize-dmg.sh"');expect(s).not.toContain('bash "$RELEASE_DIRECTORY/notarize-dmg.sh"');expect(s).toContain("local -r allowed_candidate");expect(s).toContain("candidate_inode_device");expect(s).toContain("require_bound_candidate")});
test("final artifact hash replaces canonical field and is verified before and after promotion",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain("finalArtifact.sha256");expect(s).toContain("write_final_artifact_hash");expect(s).toContain("verify_final_artifact_hash");expect(s.indexOf("write_final_artifact_hash")).toBeLessThan(s.indexOf("promote_release_set"));expect(s.lastIndexOf("verify_final_artifact_hash")).toBeGreaterThan(s.lastIndexOf("promote_release_set"))});
test("final hash differs after signing/stapling mutation and evidence agrees with bytes",()=>{const r=mkdtempSync(join(tmpdir(),"final-hash-")),f=join(r,"x.dmg"),e=join(r,"x.dmg.reproducibility.txt");writeFileSync(f,"unsigned");writeFileSync(e,"artifact.sha256=old\n");const before=run('shasum -a 256 "$F"|awk "{print \\$1}"',{F:f}).stdout.toString().trim();writeFileSync(f,"signed-stapled");const x=run('source "$S"; write_final_artifact_hash "$F" "$E"; verify_final_artifact_hash "$F" "$E"',{S:orchestrator,F:f,E:e,NOTARYTOOL_PROFILE:"unused",INDEX_RELEASE_VERSION:"1.0.0",FINAL_DIRECTORY:join(r,"never")});expect(x.exitCode).toBe(0);const text=readFileSync(e,"utf8"),final=text.match(/finalArtifact\.sha256=(\w+)/)?.[1];expect(final).toBeTruthy();expect(final).not.toBe(before);expect(final).toBe(run('shasum -a 256 "$F"|awk "{print \\$1}"',{F:f}).stdout.toString().trim())});
