import { expect, test } from "bun:test";
import { mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
const repo=resolve(import.meta.dir,"../../../.."), rel=resolve(import.meta.dir,".."), dmg=join(rel,"notarize-dmg.sh"), orchestrator=resolve(repo,"apps/mac/IndexApp/notarize.sh");
function run(s,e={}){return Bun.spawnSync(["bash","-c",s],{cwd:repo,env:{...process.env,...e},stdout:"pipe",stderr:"pipe"})}
test("standalone notarize-dmg uses the same non-publishing transform as sourced callers",()=>{const s=readFileSync(dmg,"utf8");expect(s).toContain('notarize_dmg_transform "$@"');expect(s).not.toContain("notarize_dmg_transaction");expect(s).not.toContain("notarize_dmg_internal")});
test("orchestrator sources and invokes only the immutable-source DMG transform",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain('source "$RELEASE_DIRECTORY/notarize-dmg.sh"');expect(s).not.toContain('bash "$RELEASE_DIRECTORY/notarize-dmg.sh"');expect(s).toContain('notarize_dmg_transform "$app_source" "$app_dmg"');expect(s).not.toContain("notarize_dmg_transaction")});
test("final artifact hash is written on the private output and verified before and after promotion",()=>{const d=readFileSync(dmg,"utf8"),s=readFileSync(orchestrator,"utf8");expect(d).toContain("finalArtifact.sha256");expect(d).toContain("write_candidate_final_hash");expect(s).toContain("verify_final_artifact_hash");expect(d.indexOf("write_candidate_final_hash")).toBeLessThan(d.lastIndexOf('cp -p "$candidate" "$output"'));expect(s.lastIndexOf("verify_final_artifact_hash")).toBeGreaterThan(s.lastIndexOf("promote_release_set"))});
test("final hash differs after signing/stapling mutation and evidence agrees with bytes",()=>{const r=mkdtempSync(join(tmpdir(),"final-hash-")),f=join(r,"x.dmg"),e=join(r,"x.dmg.reproducibility.txt");writeFileSync(f,"unsigned");writeFileSync(e,"artifact.sha256=old\n");const before=run('shasum -a 256 "$F"|awk "{print \\$1}"',{F:f}).stdout.toString().trim();writeFileSync(f,"signed-stapled");const x=run('source "$S"; write_candidate_final_hash "$F" "$E"',{S:dmg,F:f,E:e});expect(x.exitCode).toBe(0);const text=readFileSync(e,"utf8"),final=text.match(/finalArtifact\.sha256=(\w+)/)?.[1];expect(final).toBeTruthy();expect(final).not.toBe(before);expect(final).toBe(run('shasum -a 256 "$F"|awk "{print \\$1}"',{F:f}).stdout.toString().trim())});
