import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import YAML from "yaml";
const root=resolve(import.meta.dir,"../../../..");
const workflow=join(root,".github/workflows/mac-production-release.yml"), orchestrator=join(root,"apps/mac/release/build-release.sh"), inventory=join(root,"apps/mac/release/sealed-inventory.py"), rules=join(root,"apps/mac/release/verify-tag-ruleset.mjs"), scanner=join(root,"apps/mac/release/process-isolation.py"), prior=join(root,"apps/mac/release/verify-prior-release-metadata.sh");
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true})});
const fx=()=>{const p=mkdtempSync(join(tmpdir(),"task6-r3-"));roots.push(p);return p};
const run=(cmd,args=[],env={})=>spawnSync(cmd,args,{cwd:root,env:{...process.env,...env},encoding:"utf8"});

describe("immutable workflow and sealed handoffs",()=>{
 test("every privileged first-party step verifies reviewed source and clean GITHUB_SHA",()=>{const text=readFileSync(workflow,"utf8"),doc=YAML.parse(text),candidateSteps=doc.jobs.release.steps.filter(s=>typeof s.run==="string"&&/build-release\.sh (authorize|candidate)/.test(s.run)),publish=doc.jobs.publish.steps.find(s=>typeof s.run==="string"&&s.run.includes("build-release.sh publish"));expect(candidateSteps).toHaveLength(2);expect(publish).toBeTruthy();expect(doc.jobs.release.env).not.toHaveProperty("INDEX_RELEASE_SCRIPT_PINS");for(const s of candidateSteps){expect(s.run).toMatch(/^[ ]*[0-9a-f]{64}  apps\/mac\/release\/build-release\.sh/m);expect(s.run).toContain("/usr/bin/shasum -a 256 -c");expect(s.run).toContain("/usr/bin/git diff-index --quiet")}expect(publish.run).toMatch(/^[ ]*[0-9a-f]{64}  apps\/mac\/release\/build-release\.sh/m);expect(publish.run).toContain("/usr/bin/shasum -a 256 -c");expect(publish.run).toContain("/usr/bin/git diff-index --quiet");expect(text).not.toContain("BUILD_RELEASE_SOURCE_ONLY")});
 test("canonical inventory rejects added files, removal, symlink, and mode change",()=>{expect(()=>readFileSync(inventory,"utf8")).not.toThrow();const d=fx(),tree=join(d,"tree"),seal=join(d,"seal");mkdirSync(join(tree,"dir"),{recursive:true});writeFileSync(join(tree,"dir","a"),"a");let r=run("python3",[inventory,"create",tree,seal]);expect(r.status).toBe(0);writeFileSync(join(tree,"extra"),"x");r=run("python3",[inventory,"verify",tree,seal]);expect(r.status).not.toBe(0);rmSync(join(tree,"extra"));rmSync(join(tree,"dir","a"));r=run("python3",[inventory,"verify",tree,seal]);expect(r.status).not.toBe(0)});
 test("candidate and later publish verify sealed authority before use",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toMatch(/candidate_release\(\).*verify_prepare_seal.*verify_authorization_seal.*install_protected_credentials/s);expect(s).toMatch(/publish_release\(\).*prepare_publish_handoff.*verify_candidate_seal.*api POST/s)});
});

describe("draft REST transaction",()=>{
 test("canonical JSON PATCH is sole public step and post-PATCH is authoritatively verified",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain('{"draft":false}');expect(s).toContain('--input "$publish_body"');expect(s).toMatch(/api PATCH[\s\S]*DRAFT_PUBLISHED=1/);expect(s).toContain("verify_public_release");expect(s.indexOf("verify_uploaded_assets")).toBeLessThan(s.indexOf('{"draft":false}'))});
 test("POST response loss recovers exactly one private draft by canonical marker and ambiguity never deletes",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain("recover_created_draft_id");expect(s).toContain("exactly one matching private draft");expect(s).toContain("GITHUB_RUN_ID");expect(s).toContain("GITHUB_RUN_ATTEMPT");expect(s).toContain("INDEX_RELEASE_COMMIT");expect(s).not.toContain("/releases/tags/")});
 test("cleanup revalidates exact numeric ID and draft ownership; public releases are never deleted",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toMatch(/cleanup_created_release\(\).*GET.*CREATED_RELEASE_ID.*draft.*true.*DELETE.*CREATED_RELEASE_ID/s);expect(s).toMatch(/DRAFT_PUBLISHED.*cleanup_created_release/);expect(s).not.toMatch(/gh release delete/)});
});

describe("rules, process identity, and historical evidence",()=>{
 test("audited ruleset matcher covers GitHub globs and fail-closed malformed patterns",()=>{expect(()=>readFileSync(rules,"utf8")).not.toThrow();const base={id:7,enforcement:"active",target:"tag",bypass_actors:[],conditions:{ref_name:{include:["refs/tags/v*"],exclude:[]}},rules:[{type:"update"},{type:"deletion"}]};for(const include of [["refs/tags/v*"],["refs/tags/v?.?.?"],["refs/tags/v1.0.0"]]){base.conditions.ref_name.include=include;const r=run("bun",[rules,JSON.stringify(base),"v1.0.0","7"]);expect(r.status,include[0]).toBe(0)}base.conditions.ref_name.exclude=["refs/tags/v*"];expect(run("bun",[rules,JSON.stringify(base),"v1.0.0","7"]).status).not.toBe(0);base.conditions.ref_name.exclude=[];base.conditions.ref_name.include=["refs/tags/[bad"];expect(run("bun",[rules,JSON.stringify(base),"v1.0.0","7"]).status).not.toBe(0)});
 test("process scanner verifies protected runner paths and hashes through the production algorithm",()=>{const src=readFileSync(scanner,"utf8");for(const x of ["--listener-path","--listener-sha256","--worker-path","--worker-sha256","proc_pidpath"])expect(src).toContain(x);const text=readFileSync(workflow,"utf8");for(const x of ["INDEX_RELEASE_RUNNER_LISTENER_PATH","INDEX_RELEASE_RUNNER_LISTENER_SHA256","INDEX_RELEASE_RUNNER_WORKER_PATH","INDEX_RELEASE_RUNNER_WORKER_SHA256"])expect(text).toContain(x)});
 test("historical verifier binds downloaded DMG bytes, sizes, digests, URLs, and exact full inventory",()=>{const v=readFileSync(prior,"utf8"),s=readFileSync(orchestrator,"utf8");expect(v).toContain("FINAL_DIR");expect(v).toContain("SHA256SUMS");expect(v).toContain("artifact bytes");for(const n of ["macos-release.json","macos-release.cms","Index-macOS-","IndexConnector-","SHA256SUMS"])expect(s).toContain(n);expect(s).toContain("historical macOS release has incomplete or duplicate full asset set")});
 test("candidate restores noninteractive Keychain timeout and partition list",()=>{const s=readFileSync(orchestrator,"utf8");expect(s).toContain("security set-keychain-settings -lut 21600");expect(s).toContain("security set-key-partition-list -S apple-tool:,apple:")});
});
