import { afterEach, describe, expect, test } from "bun:test";
import { chmodSync, mkdtempSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { tmpdir } from "node:os";
import { spawnSync } from "node:child_process";
import YAML from "yaml";
const root=resolve(import.meta.dir,"../../../..");
const workflowPath=join(root,".github/workflows/mac-production-release.yml"), script=join(root,"apps/mac/release/build-release.sh"), scanner=join(root,"apps/mac/release/process-isolation.py"), prior=join(root,"apps/mac/release/verify-prior-release-metadata.sh");
const roots=[];afterEach(()=>{while(roots.length)rmSync(roots.pop(),{recursive:true,force:true})});
function fx(){const p=mkdtempSync(join(tmpdir(),"task6-r2-"));roots.push(p);return p}
function run(cmd,args=[],env={},cwd=root){return spawnSync(cmd,args,{cwd,env:{...process.env,...env},encoding:"utf8"})}
function parsed(){return YAML.parse(readFileSync(workflowPath,"utf8"))}
const apple=["INDEX_DEVELOPER_ID_CERTIFICATE_P12","INDEX_DEVELOPER_ID_CERTIFICATE_PASSWORD","INDEX_APP_PROVISIONING_PROFILE_BASE64","INDEX_CONNECTOR_PROVISIONING_PROFILE_BASE64","INDEX_NOTARY_API_KEY_BASE64","INDEX_NOTARY_KEY_ID","INDEX_NOTARY_ISSUER_ID"];

describe("structurally split workflow",()=>{
 test("prepare, authorize, candidate, attestation, and publish have disjoint authority",()=>{const steps=parsed().jobs.release.steps;const by=(fragment)=>steps.find(s=>typeof s.run==="string"&&s.run.includes(fragment));const prepare=by(" prepare"),authorize=by(" authorize"),candidate=by(" candidate"),publish=by(" publish");expect(prepare).toBeTruthy();expect(authorize).toBeTruthy();expect(candidate).toBeTruthy();expect(publish).toBeTruthy();expect(prepare.env??{}).not.toHaveProperty("GH_TOKEN");for(const n of apple)expect(prepare.env??{}).not.toHaveProperty(n);expect(authorize.env.GH_TOKEN).toBe("${{ github.token }}");for(const n of apple)expect(authorize.env??{}).not.toHaveProperty(n);expect(candidate.env??{}).not.toHaveProperty("GH_TOKEN");for(const n of apple)expect(candidate.env[n]).toBe(`\${{ secrets.${n} }}`);expect(publish.env.GH_TOKEN).toBe("${{ github.token }}");for(const n of apple)expect(publish.env??{}).not.toHaveProperty(n);for(const s of steps.filter(s=>s.uses))expect(JSON.stringify(s.env??{})).not.toMatch(/secrets\.|GH_TOKEN/)});
 test("all action pins and expressions survive YAML parsing",()=>{const doc=parsed();expect(doc.on.push.tags).toEqual(["v*"]);expect(doc.permissions).toEqual({contents:"write","id-token":"write",attestations:"write"});for(const s of doc.jobs.release.steps.filter(s=>s.uses))expect(s.uses).toMatch(/@[0-9a-f]{40}$/);expect(readFileSync(workflowPath,"utf8")).not.toMatch(/gh release create|gh release upload/)});
});

describe("production entrypoint semantics",()=>{
 test("prepare parent process has no secret names or values",()=>{const src=readFileSync(script,"utf8");expect(src).toContain("prepare_release");expect(src).toContain("assert_secret_environment_absent");expect(src).not.toContain("INDEX_RELEASE_TEST_")});
 test("draft transaction captures POST id directly, verifies uploads by numeric ID, and PATCH is sole public step",()=>{const src=readFileSync(script,"utf8");expect(src).toContain('POST "/repos/${GITHUB_REPOSITORY}/releases"');expect(src).toContain("upload_url");expect(src).toContain('GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}"');expect(src).toContain('DELETE "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}"');expect(src).not.toContain("/releases/tags/${INDEX_RELEASE_TAG}");expect((src.match(/draft:='false'/g)??[])).toHaveLength(1);expect(src.indexOf("verify_uploaded_assets")).toBeLessThan(src.indexOf("draft:='false'"))});
 test("ruleset verifier rejects exclusions, bypass actors, and non-active enforcement",()=>{const dir=fx(),repo=join(dir,"repo"),bare=join(dir,"origin.git"),bin=join(dir,"bin");mkdirSync(bin);run("git",["init",repo]);run("git",["-C",repo,"config","user.email","a@b.c"]);run("git",["-C",repo,"config","user.name","a"]);writeFileSync(join(repo,"x"),"x");run("git",["-C",repo,"add","x"]);run("git",["-C",repo,"commit","-m","x"]);run("git",["init","--bare",bare]);run("git",["-C",repo,"remote","add","origin",bare]);run("git",["-C",repo,"tag","-a","v1.0.0","-m","release"]);run("git",["-C",repo,"push","origin","HEAD","refs/tags/v1.0.0"]);const sha=run("git",["-C",repo,"rev-parse","HEAD"]).stdout.trim();for(const mutation of [r=>r.enforcement="evaluate",r=>r.bypass_actors=[{actor_id:1,bypass_mode:"always"}],r=>r.conditions.ref_name.exclude=["refs/tags/v1.0.0"]]){const rules={id:7,enforcement:"active",target:"tag",bypass_actors:[],conditions:{ref_name:{include:["refs/tags/v1.0.0"],exclude:[]}},rules:[{type:"update"},{type:"deletion"}]};mutation(rules);writeFileSync(join(bin,"gh"),`#!/bin/sh\nprintf '%s' '${JSON.stringify(rules)}'\n`);chmodSync(join(bin,"gh"),0o755);const r=run("bash",["-c",'export BUILD_RELEASE_SOURCE_ONLY=1; source "$S"; REPO_ROOT="$R"; validate_remote_annotated_tag'],{S:script,R:repo,PATH:`${bin}:${process.env.PATH}`,INDEX_RELEASE_TAG:"v1.0.0",INDEX_RELEASE_COMMIT:sha,INDEX_RELEASE_TAG_RULESET_ID:"7",GITHUB_REPOSITORY:"indexnetwork/index"});expect(r.status).not.toBe(0)}});
 test("process scanner accepts shaped ancestry/children and rejects detached exact-path and late process",()=>{expect(()=>readFileSync(scanner,"utf8")).not.toThrow();const dir=fx(),allow=join(dir,"allow"),snap=join(dir,"snap");writeFileSync(allow,"/sbin/launchd\n/usr/libexec/UserEventAgent\n");const digest=new Bun.CryptoHasher("sha256").update(readFileSync(allow)).digest("hex");writeFileSync(snap,"1\t0\t501\t/sbin/launchd\n10\t1\t501\t/opt/actions-runner/bin/Runner.Listener\n11\t10\t501\t/opt/actions-runner/bin/Runner.Worker\n12\t11\t501\t/bin/bash\n13\t12\t501\t/usr/bin/python3\n20\t1\t501\t/usr/libexec/UserEventAgent\n");let r=run("python3",[scanner,"--snapshot",snap,"--root-pid","12","--uid","501","--allowlist",allow,"--allowlist-sha256",digest]);expect(r.status).toBe(0);writeFileSync(snap,readFileSync(snap,"utf8")+"30\t1\t501\t/opt/actions-runner/bin/Runner.Worker\n");r=run("python3",[scanner,"--snapshot",snap,"--root-pid","12","--uid","501","--allowlist",allow,"--allowlist-sha256",digest]);expect(r.status).not.toBe(0)});
 test("historical semver is canonical and discovery does not depend on release name",()=>{expect(readFileSync(prior,"utf8")).toContain("(?:0|[1-9][0-9]*)");const src=readFileSync(script,"utf8");expect(src).toContain(".draft, .prerelease");expect(src).not.toMatch(/\$tag.*=~ \^v/);expect(src).toContain("duplicate historical macOS asset")});
});
