/**
 * QuestionerAdapter — Drizzle implementation of the QuestionerDatabase
 * contract from @indexnetwork/protocol.
 *
 * Persists structured questions generated by the QuestionerAgent and
 * exposes retrieval/mutation for the question lifecycle (pending → answered
 * or dismissed).
 *
 * Per adapter layering rules the local types are defined here; structural
 * alignment with protocol interfaces is verified by the compile-time
 * alignment spec.
 */

import { eq, and, sql } from 'drizzle-orm';

import { questions } from '../schemas/database.schema';
import type { QuestionDetection, QuestionActor } from '../schemas/database.schema';
import type { DrizzleDB } from '../lib/drizzle/drizzle';
import { QuestionEvents } from '../events/question.event';

// ─── Local adapter types (structurally aligned with protocol contracts) ───────

/** Detection context describing how/where a question was generated. */
export interface AdapterQuestionDetection {
  mode: 'discovery' | 'intent' | 'profile' | 'negotiation';
  sourceType: string;
  sourceId: string;
  triggeredBy?: string;
  timestamp: string;
}

/** An actor targeted by a question (typically the user who should answer). */
export interface AdapterQuestionActor {
  userId: string;
  networkId?: string;
  role: 'subject';
}

/** The user-facing question payload (title, prompt, options). */
export interface AdapterQuestionPayload {
  title: string;
  prompt: string;
  options: Array<{ label: string; description: string }>;
  multiSelect: boolean;
}

/** Answer recorded when a user responds to a question. */
export interface AdapterQuestionAnswer {
  selectedOptions: string[];
  freeText?: string;
  answeredBy: string;
  answeredAt: string;
}

/** Input shape for persisting a new question (no DB id or status yet). */
export interface AdapterPersistableQuestion {
  detection: AdapterQuestionDetection;
  actors: AdapterQuestionActor[];
  payload: AdapterQuestionPayload;
  strategy:
    | 'refine_intent'
    | 'surface_missing_detail'
    | 'open_adjacent_thread'
    | 'reflective_summary'
    | 'surface_emergent_knowledge';
}

/** A question row returned from the database. */
export interface AdapterPersistedQuestion {
  id: string;
  detection: AdapterQuestionDetection;
  actors: AdapterQuestionActor[];
  payload: AdapterQuestionPayload;
  status: 'pending' | 'answered' | 'dismissed';
  answer: AdapterQuestionAnswer | null;
  createdAt: string;
}

/** Optional filters for the `findPending` query. */
export interface AdapterQuestionFilters {
  mode?: 'discovery' | 'intent' | 'profile' | 'negotiation';
  sourceType?: string;
  sourceId?: string;
}

/**
 * QuestionerAdapter — persists and queries the `questions` table.
 *
 * Accepts a Drizzle DB instance via constructor injection for testability.
 */
export class QuestionerAdapter {
  constructor(private readonly db: DrizzleDB) {}

  /**
   * Persist a batch of generated questions.
   *
   * @param batch - Questions to insert (up to 3 per generation).
   * @returns The IDs of the inserted rows.
   */
  async persist(batch: AdapterPersistableQuestion[]): Promise<string[]> {
    if (batch.length === 0) return [];
    const rows = batch.map((q) => ({
      detection: { ...q.detection, strategy: q.strategy } satisfies QuestionDetection,
      actors: q.actors as QuestionActor[],
      payload: q.payload,
      status: 'pending' as const,
    }));

    const inserted = await this.db.insert(questions).values(rows).returning({ id: questions.id });
    return inserted.map((r) => r.id);
  }

  /**
   * Find pending questions for a given user, optionally filtered by
   * detection mode, source type, or source id.
   *
   * Uses a jsonb containment query (`@>`) to locate rows where the
   * `actors` array includes an entry with the target userId.
   *
   * @param userId  - The user to find pending questions for.
   * @param filters - Optional narrowing filters.
   * @returns Pending questions ordered by creation time (oldest first).
   */
  async findPending(
    userId: string,
    filters?: AdapterQuestionFilters,
  ): Promise<AdapterPersistedQuestion[]> {
    const conditions = [
      eq(questions.status, 'pending'),
      sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
    ];

    if (filters?.mode) {
      conditions.push(sql`${questions.detection}->>'mode' = ${filters.mode}`);
    }
    if (filters?.sourceType) {
      conditions.push(sql`${questions.detection}->>'sourceType' = ${filters.sourceType}`);
    }
    if (filters?.sourceId) {
      conditions.push(sql`${questions.detection}->>'sourceId' = ${filters.sourceId}`);
    }

    const rows = await this.db
      .select()
      .from(questions)
      .where(and(...conditions))
      .orderBy(questions.createdAt);

    return rows.map(toPersistedQuestion);
  }

  /**
   * Record an answer for a question, setting its status to `answered`.
   * Emits `QuestionEvents.onAnswered` after persisting the answer.
   * Only updates the question if the user is listed as an actor.
   *
   * @param questionId - ID of the question to answer.
   * @param userId     - Authenticated user; must be an actor on the question.
   * @param answer     - The user's response data.
   * @returns `true` if a row was updated, `false` if no matching question found.
   */
  async answer(questionId: string, userId: string, answer: AdapterQuestionAnswer): Promise<boolean> {
    const ownershipCheck = and(
      eq(questions.id, questionId),
      sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
    );

    const [existing] = await this.db
      .select()
      .from(questions)
      .where(ownershipCheck);

    if (!existing) return false;

    await this.db
      .update(questions)
      .set({ status: 'answered', answer })
      .where(ownershipCheck);

    const detection = existing.detection as AdapterQuestionDetection;
    const actors = existing.actors as AdapterQuestionActor[];
    const firstActor = actors[0];
    if (firstActor) {
      QuestionEvents.onAnswered({
        questionId,
        userId: firstActor.userId,
        mode: detection.mode,
        sourceType: detection.sourceType,
        sourceId: detection.sourceId,
        answer,
      });
    }

    return true;
  }

  /**
   * Dismiss a question, setting its status to `dismissed`.
   * Only updates the question if the user is listed as an actor.
   *
   * @param questionId - ID of the question to dismiss.
   * @param userId     - Authenticated user; must be an actor on the question.
   * @returns `true` if a row was updated, `false` if no matching question found.
   */
  async dismiss(questionId: string, userId: string): Promise<boolean> {
    const ownershipCheck = and(
      eq(questions.id, questionId),
      sql`${questions.actors}::jsonb @> ${JSON.stringify([{ userId }])}::jsonb`,
    );

    const [existing] = await this.db
      .select({ id: questions.id })
      .from(questions)
      .where(ownershipCheck);

    if (!existing) return false;

    await this.db
      .update(questions)
      .set({ status: 'dismissed' })
      .where(ownershipCheck);

    return true;
  }
}

// ─── Internal helpers ────────────────────────────────────────────────────────

/** Map a raw Drizzle row into the adapter's persisted-question shape. */
function toPersistedQuestion(
  row: typeof questions.$inferSelect,
): AdapterPersistedQuestion {
  return {
    id: row.id,
    detection: row.detection as AdapterQuestionDetection,
    actors: row.actors as AdapterQuestionActor[],
    payload: row.payload as AdapterQuestionPayload,
    status: row.status,
    answer: (row.answer as AdapterQuestionAnswer) ?? null,
    createdAt: row.createdAt.toISOString(),
  };
}
