// Fake-but-coherent data for the halo prototype.
// All names invented; any resemblance to real people is coincidental.

const EVENT = {
  name: "synthesis",
  venue: "the hex",
  neighborhood: "brooklyn",
  date: "thu · may 18",
  doors: "20:00",
  attending: 247,
  arrived: 88,
};

// Onboarding questions — agent-led, conversational
const ONBOARDING_STEPS = [
  {
    id: "intent",
    prompt: "what would make tonight a win?",
    hint: "be honest — i'll keep it to myself.",
    placeholder: "two good conversations, maybe a co-founder lead…",
    examples: ["one real conversation", "leave with a co-founder lead", "find a running buddy", "just escape my apartment"],
  },
  {
    id: "edges",
    prompt: "what're you sitting with lately?",
    hint: "what's on your mind. it helps me pattern-match.",
    placeholder: "rewriting our onboarding · learning portuguese · my sister's wedding…",
    examples: ["leaving a six-year job", "ml infra at small scale", "starting to paint again", "tired of saas"],
  },
  {
    id: "off-limits",
    prompt: "anything off-limits?",
    hint: "topics, people, or vibes i should route you away from.",
    placeholder: "no recruiting pitches · skip crypto talk · don't introduce me to my ex's friends",
    examples: ["no crypto", "no sales pitches", "skip anyone from acme co"],
  },
  {
    id: "shape",
    prompt: "how do you want me to operate?",
    hint: "i can be a busybody, or i can sit quietly.",
    choices: [
      { value: "quiet", label: "quiet", sub: "introduce 1–2 high-signal people; otherwise nothing." },
      { value: "warm", label: "warm", sub: "surface a handful, ask before negotiating." },
      { value: "active", label: "active", sub: "keep the pipeline busy; you can ignore most of it." },
    ],
  },
];

// People at the event — visible from the start.
const PEOPLE = [
  {
    id: "maren", name: "maren k.",
    blurb: "ex-stripe infra. now building something around payouts for crews.",
    location: "near the bar", arrived: -8, distance: "12m", mutuals: 3,
    signals: ["payments", "small teams", "leaving big-co"],
    overlap: ["leaving a six-year job", "ml infra at small scale"],
    score: 0.94, status: "warm",
    pitchFromAgent: "she's also one foot out of a long stint. your edges line up almost exactly.",
    introVia: "anya (last month, at the pier)",
  },
  {
    id: "ren", name: "ren a.",
    blurb: "documentary editor, currently doing a piece on calm tech.",
    location: "smoking patio", arrived: -22, distance: "31m", mutuals: 1,
    signals: ["calm tech", "long-form", "interviewing"],
    overlap: ["tired of saas"],
    score: 0.81, status: "considering",
    pitchFromAgent: "wants to interview people who left noisy products. could be light or substantial — your call.",
    introVia: "open intro",
  },
  {
    id: "ilya", name: "ilya s.",
    blurb: "trains models on weekends, runs a tiny rationality reading group.",
    location: "lobby", arrived: -2, distance: "8m", mutuals: 0,
    signals: ["ml infra", "reading group", "quiet"],
    overlap: ["ml infra at small scale"],
    score: 0.78, status: "negotiating",
    pitchFromAgent: "his agent flagged the same infra paper twice this week. low-pressure.",
    introVia: "cold (his agent reached first)",
  },
  {
    id: "phoebe", name: "phoebe l.",
    blurb: "left her saas co. last week. learning to paint, allegedly.",
    location: "upstairs", arrived: -34, distance: "44m", mutuals: 2,
    signals: ["transition", "painting", "tired of saas"],
    overlap: ["tired of saas", "starting to paint again"],
    score: 0.72, status: "warm",
    pitchFromAgent: "fresh out of the same trench. she'd probably appreciate not being asked about the company.",
    introVia: "open intro",
  },
  {
    id: "kai", name: "kai m.",
    blurb: "runs a co-op of three. looking for a technical partner who likes payments.",
    location: "main room", arrived: -12, distance: "19m", mutuals: 0,
    signals: ["co-founder", "payments", "crews"],
    overlap: [],
    score: 0.69, status: "considering",
    pitchFromAgent: "explicit co-founder search. matches your 'co-founder lead' goal but slightly off your stack.",
    introVia: "open intro",
  },
  {
    id: "ola", name: "ola b.",
    blurb: "running a half-marathon in june. translates portuguese poetry on the side.",
    location: "main room", arrived: -45, distance: "22m", mutuals: 0,
    signals: ["running", "portuguese", "books"],
    overlap: ["learning portuguese"],
    score: 0.61, status: "warm",
    pitchFromAgent: "soft match — running + portuguese. low stakes, easy intro.",
    introVia: "open intro",
  },
  {
    id: "noor", name: "noor a.",
    blurb: "sound designer; finishing a debut ambient record.",
    location: "back garden", arrived: -27, distance: "38m", mutuals: 2,
    signals: ["music", "calm tech", "long-form"],
    overlap: ["tired of saas"],
    score: 0.66, status: "considering",
    pitchFromAgent: "shares your taste in slow products. would probably like meeting ren more than you.",
    introVia: "via dani's network",
  },
  {
    id: "jules", name: "jules e.",
    blurb: "community manager at a small writer collective. organizes monthly hikes.",
    location: "main room", arrived: -18, distance: "24m", mutuals: 4,
    signals: ["community", "writing", "outdoors"],
    overlap: [],
    score: 0.58, status: "warm",
    pitchFromAgent: "high mutuals · would broaden your friend graph more than your work graph.",
    introVia: "open intro",
  },
  {
    id: "vik", name: "vik k.",
    blurb: "researcher at an ai-policy nonprofit. recently moved from london.",
    location: "lobby", arrived: -6, distance: "10m", mutuals: 1,
    signals: ["ai policy", "research", "newly arrived"],
    overlap: ["ml infra at small scale"],
    score: 0.64, status: "considering",
    pitchFromAgent: "tangential to your edges. interesting if you want to widen your taste, not your wallet.",
    introVia: "open intro",
  },
  {
    id: "mira", name: "mira j.",
    blurb: "chef, opening a 12-seat tasting menu spot this fall. funded it herself.",
    location: "upstairs", arrived: -38, distance: "46m", mutuals: 0,
    signals: ["food", "small business", "self-funded"],
    overlap: ["leaving a six-year job"],
    score: 0.55, status: "warm",
    pitchFromAgent: "different field, parallel trajectory. she'd be a good 'this is what after looks like' conversation.",
    introVia: "open intro",
  },
];

// Deep pool — agents the pipeline can pull in when it expands.
// Not visible by default; flip `hidden:false` on expansion clarifiers.
const POOL = [
  {
    id: "yael", name: "yael m.", hidden: true,
    blurb: "fourth co-founder hunt this year. doesn't sugarcoat.",
    location: "balcony", arrived: -6, distance: "28m", mutuals: 1,
    signals: ["co-founder", "payments", "honest"], overlap: ["leaving a six-year job"],
    score: 0.74, status: "considering",
    pitchFromAgent: "explicit co-founder hunt. she's also exiting big-co. high signal but loud.",
    introVia: "open intro · upstairs cluster",
  },
  {
    id: "dani", name: "dani r.", hidden: true,
    blurb: "writes a niche newsletter on small-team infrastructure.",
    location: "smoking patio", arrived: -19, distance: "35m", mutuals: 2,
    signals: ["ml infra", "writing", "small teams"], overlap: ["ml infra at small scale"],
    score: 0.71, status: "considering",
    pitchFromAgent: "low-pressure. she'd love a conversation, not a transaction.",
    introVia: "open intro",
  },
  {
    id: "sasha", name: "sasha p.", hidden: true,
    blurb: "left her startup last march. now consulting for crews of three.",
    location: "main room", arrived: -28, distance: "16m", mutuals: 0,
    signals: ["payments", "crews", "consulting"], overlap: [],
    score: 0.68, status: "considering",
    pitchFromAgent: "adjacent to your edges. queued if you want to widen.",
    introVia: "open intro · upstairs cluster",
  },
  {
    id: "theo", name: "theo c.", hidden: true,
    blurb: "ex-research scientist. now teaches kids to code in red hook.",
    location: "upstairs", arrived: -15, distance: "44m", mutuals: 1,
    signals: ["ml infra", "teaching", "tired of saas"], overlap: ["ml infra at small scale", "tired of saas"],
    score: 0.77, status: "warm",
    pitchFromAgent: "the second-strongest overlap upstairs. flagged when 6 agents converged on the balcony.",
    introVia: "agent-to-agent",
  },
  {
    id: "alex", name: "alex h.", hidden: true,
    blurb: "early-stage investor. low-key tonight, not in pitch mode.",
    location: "main room", arrived: -42, distance: "20m", mutuals: 2,
    signals: ["investor", "small checks", "off-duty"],
    overlap: [],
    score: 0.52, status: "considering",
    pitchFromAgent: "investor energy, but his agent flagged 'do not pitch tonight'. easy if you respect that.",
    introVia: "open intro · vouched by dani",
  },
  {
    id: "nia", name: "nia f.", hidden: true,
    blurb: "ux researcher, just left big-tech. doing field studies for fun.",
    location: "smoking patio", arrived: -11, distance: "33m", mutuals: 1,
    signals: ["research", "leaving big-co", "field work"],
    overlap: ["leaving a six-year job"],
    score: 0.69, status: "warm",
    pitchFromAgent: "would be good with maren or phoebe. consider routing her toward them instead.",
    introVia: "open intro",
  },
  {
    id: "omar", name: "omar t.", hidden: true,
    blurb: "climber, photographer. just back from patagonia. between things.",
    location: "back garden", arrived: -25, distance: "41m", mutuals: 0,
    signals: ["climbing", "photography", "between things"],
    overlap: [],
    score: 0.48, status: "considering",
    pitchFromAgent: "wild card. only surfaces if you ask for 'unrelated to work'.",
    introVia: "ambient · overheard",
  },
  {
    id: "harper", name: "harper q.", hidden: true,
    blurb: "writes copy by day; does stand-up at the brick on wednesdays.",
    location: "main room", arrived: -31, distance: "26m", mutuals: 3,
    signals: ["writing", "comedy", "high-mutuals"],
    overlap: [],
    score: 0.51, status: "warm",
    pitchFromAgent: "high trust · 3 mutuals all rate her warmly. would probably make you laugh tonight.",
    introVia: "open intro · vouched by jules",
  },
  {
    id: "tomas", name: "tomás v.", hidden: true,
    blurb: "engineer at a small newsroom. builds tools for journalists.",
    location: "lobby", arrived: -9, distance: "14m", mutuals: 0,
    signals: ["journalism tools", "small teams", "newsroom"],
    overlap: ["ml infra at small scale"],
    score: 0.6, status: "considering",
    pitchFromAgent: "infra-adjacent and unusual. would not waste your time.",
    introVia: "agent-to-agent",
  },
];

// Background "field events" — the ambient ticker in the right column header.
const FIELD_EVENTS = [
  { kind: "inspect",   text: "inspected 6 nearby · 4 didn't match your edges." },
  { kind: "negotiate", text: "your agent ↔ ilya's agent · trading context." },
  { kind: "passed",    text: "passed on 'enterprise sales' cluster — off-limits." },
  { kind: "warm",      text: "phoebe's agent warmed up · she's open to a low-key intro." },
  { kind: "inspect",   text: "scanning the smoking patio · 9 new arrivals." },
  { kind: "negotiate", text: "kai's agent counter-proposed: 'after his pitch round.'" },
  { kind: "arrived",   text: "maren just stepped inside. 12m from you." },
  { kind: "passed",    text: "ola's agent declined — she's mid-conversation." },
  { kind: "warm",      text: "ren's agent shared their interview brief." },
  { kind: "inspect",   text: "indexed 22 conversations within earshot of the bar." },
  { kind: "negotiate", text: "two agents you've never met are arguing about you." },
  { kind: "warm",      text: "you came up in a thread upstairs · positively." },
  { kind: "negotiate", text: "harper's agent vouched for jules · trust score bumped." },
  { kind: "warm",      text: "noor's record came up in a separate cluster · tangential signal." },
  { kind: "passed",    text: "an unknown agent tried to surface you · denied (off-limits)." },
];

// Ambient agent observations — appear in the feed without expecting an answer.
const AMBIENT_NOTES = [
  "i declined a recruiter intro on your behalf · they were off-limits.",
  "saved theo to your follow-up list for tomorrow.",
  "your maren thread cooled · she stepped outside for a minute.",
  "ilya's agent went idle · he's deep in conversation. holding.",
  "merged two duplicate signals · same person, different mutuals introduced them.",
  "the bar cluster just thinned · pipeline tilting upstairs.",
  "noted: you've been on the same floor for 18 min. want me to nudge?",
  "no urgent moves. i'm just watching.",
  "filed a low-priority candidate for next week's event.",
  "rotated 3 candidates out of the pool · they left.",
  "the room temp jumped 2 degrees · cluster around the heater forming.",
  "jules's hike group came up twice in 10 min · adjacent signal.",
  "harper's set just ended at the brick · she's reportedly on her way over.",
  "expired 2 stale candidates · neither moved in 22 min.",
  "your agent is humming.",
];

// Clarifying questions — proactively pushed into the left feed over time.
// source: "agent" | "individual" | "collective" | "room"
// effect: "expanding" | "narrowing" | "focused" | "neutral"
const CLARIFIERS = [
  {
    id: "q1", source: "collective", effect: "narrowing",
    sourceMeta: { count: 9, of: "agents tonight" },
    text: "nine agents in the room have flagged 'leaving big-co' as a sticky thread tonight. anchor your night around that cluster, or stay broad?",
    chips: ["anchor me there", "stay broad", "show me the cluster"],
    triggersHint: "narrows your pipeline to ~3 people instead of ~12.",
  },
  {
    id: "q2", source: "individual", effect: "neutral",
    sourceMeta: { name: "ilya's agent" },
    text: "ilya's agent asked if you'd skim a 1-pager before you meet. yes / no / skim it for me?",
    chips: ["yes, send it", "skim it for me", "skip the prep"],
    triggersHint: "ilya · negotiating",
  },
  {
    id: "q3", source: "room", effect: "narrowing",
    sourceMeta: { count: 47, of: "overheard conversations" },
    text: "the room is splitting into two clusters — ml/infra upstairs, payments + crews downstairs. commit to one floor, or float?",
    chips: ["upstairs", "downstairs", "let me float"],
    triggersHint: "shapes which half of the pipeline expands.",
  },
  {
    id: "q4", source: "individual", effect: "neutral",
    sourceMeta: { name: "ren's agent" },
    text: "ren wants 20 min on camera before the night ends. happy to mention, decline politely, or hold for later?",
    chips: ["mention it casually", "decline politely", "hold for later"],
    triggersHint: "ren · considering",
  },
  {
    id: "q5", source: "collective", effect: "expanding",
    sourceMeta: { count: 12, of: "mentions in the last 20 min" },
    text: "'co-founder' has come up 12 times in nearby conversations. want me to widen the pipeline toward founders, or keep it tight?",
    chips: ["widen", "keep it tight", "only if signal's strong"],
    triggersHint: "expands pipeline · 9 new candidates queued.",
  },
  {
    id: "q6", source: "room", effect: "expanding",
    sourceMeta: { count: 3, of: "rooms scanned" },
    text: "someone three rooms away just said 'i'm tired of saas' out loud. interested, or ignore the ambient pickups?",
    chips: ["go closer", "queue them", "ignore ambient"],
    triggersHint: "passive listening · phoebe-adjacent.",
  },
  {
    id: "q7", source: "collective", effect: "narrowing",
    sourceMeta: { count: 6, of: "agents converging" },
    text: "six agents are independently trying to introduce you to people on the upstairs balcony. converge there, or stay grounded?",
    chips: ["go upstairs", "stay here", "split the difference"],
    triggersHint: "narrows pipeline to upstairs · drops 4 candidates.",
  },
  {
    id: "q8", source: "individual", effect: "neutral",
    sourceMeta: { name: "kai's agent" },
    text: "kai is doing an explicit co-founder pitch round. one of three. should i let you in?",
    chips: ["queue me", "not tonight", "tell me more"],
    triggersHint: "kai · considering",
  },
  {
    id: "q9", source: "collective", effect: "expanding",
    sourceMeta: { count: 14, of: "agents nearby" },
    text: "14 agents are pinging me about 'tired of saas' as the dominant cluster tonight. lean into it, or branch wider on purpose?",
    chips: ["lean in", "branch wider", "ignore the cluster"],
    triggersHint: "leaning in pulls 5 saas-adjacent · branching opens 7 unrelated.",
  },
  {
    id: "q10", source: "agent", effect: "narrowing",
    text: "your energy looks low — 47 min in, only one conversation. should i drop noisy candidates and keep only the strongest 3?",
    chips: ["yes, drop noise", "keep them", "tighten gradually"],
    triggersHint: "drops 6 candidates immediately · keeps 3 high-signal.",
  },
  {
    id: "q11", source: "room", effect: "narrowing",
    sourceMeta: { count: 22, of: "people on this floor" },
    text: "the bar cluster is dispersing — they're moving to the patio. follow the cluster, or stay where you are?",
    chips: ["follow them", "stay put", "send me a tap when they settle"],
    triggersHint: "follow → pipeline narrows to patio-only · 4 candidates drop.",
  },
  {
    id: "q12", source: "individual", effect: "neutral",
    sourceMeta: { name: "phoebe's agent" },
    text: "phoebe asks: are you bringing recruiting energy, or actually here to wind down? she'll opt out if it's the former.",
    chips: ["just here to wind down", "honestly mixed", "be honest with her"],
    triggersHint: "phoebe · gating the intro.",
  },
  {
    id: "q13", source: "collective", effect: "expanding",
    sourceMeta: { count: 4, of: "agents flagging the same person" },
    text: "four separate agents independently flagged the same person to me — sasha p. — none of us know why she scores high. dig in?",
    chips: ["surface her", "show me the reasoning", "skip"],
    triggersHint: "surface · adds sasha to discovered.",
  },
  {
    id: "q14", source: "room", effect: "neutral",
    sourceMeta: { count: 2, of: "overheard fragments" },
    text: "i caught two people separately mention your last project. neither tagged you. want me to find them, or let it stay ambient?",
    chips: ["find them", "let it stay ambient", "tell me who first"],
    triggersHint: "find · adds 2 pending intros.",
  },
  {
    id: "q15", source: "agent", effect: "focused",
    text: "maren and ilya are both 12m away in opposite directions. i can only push one cleanly in the next 10 min. pick?",
    chips: ["maren", "ilya", "you pick"],
    triggersHint: "focuses pipeline on one · the other stays warm.",
  },
  {
    id: "q16", source: "collective", effect: "narrowing",
    sourceMeta: { count: 7, of: "agents reporting a pattern" },
    text: "seven agents are reporting the same pattern: the second hour is always quieter than the first. cut your night short, extend, or hold steady?",
    chips: ["cut short at 22:00", "extend if signal stays", "hold steady"],
    triggersHint: "cut short narrows to top 2 only · extend opens the pool again.",
  },
  {
    id: "q17", source: "individual", effect: "expanding",
    sourceMeta: { name: "theo's agent" },
    text: "theo just shared a list of three people he thinks you should meet. trust his taste, or filter it through me?",
    chips: ["trust theo", "filter it through you", "show me the list"],
    triggersHint: "trust theo · adds 3 pre-vetted candidates.",
  },
  {
    id: "q18", source: "room", effect: "narrowing",
    sourceMeta: { count: 1, of: "off-limits cluster forming" },
    text: "a recruiting cluster just formed near the entrance. you flagged 'no recruiting'. want me to keep you on the opposite side?",
    chips: ["keep me away", "i can handle it", "show me the cluster"],
    triggersHint: "keep away · re-routes pipeline upstairs.",
  },
  {
    id: "q19", source: "agent", effect: "neutral",
    text: "two of your warm candidates haven't moved in 18 min. ping their agents, or let them breathe?",
    chips: ["ping them", "let them breathe", "ping just one"],
    triggersHint: "neutral · slight chance of warming or expiring.",
  },
  {
    id: "q20", source: "collective", effect: "focused",
    sourceMeta: { count: 5, of: "agents agreeing" },
    text: "five agents independently agree maren is your strongest match tonight. commit to her, or keep options open?",
    chips: ["commit", "keep options", "let me see her thread first"],
    triggersHint: "commit · pipeline focuses on maren only.",
  },
  {
    id: "q21", source: "individual", effect: "expanding",
    sourceMeta: { name: "dani's agent" },
    text: "dani wants to introduce you to two of her friends who just walked in. she vouches. accept blind, or vet first?",
    chips: ["accept blind", "vet first", "decline politely"],
    triggersHint: "accept blind · adds 2 candidates with high trust.",
  },
  {
    id: "q22", source: "room", effect: "focused",
    sourceMeta: { count: 1, of: "moment forming" },
    text: "a quiet circle just formed by the back window — 4 people, no laptops, no pitches. slip in, observe, or pass?",
    chips: ["slip in", "observe from nearby", "pass"],
    triggersHint: "slip in · pipeline focuses on the circle.",
  },
];

window.HALO_DATA = { EVENT, ONBOARDING_STEPS, PEOPLE, POOL, CLARIFIERS, FIELD_EVENTS, AMBIENT_NOTES };
