import { z } from "zod";

import type { DefineTool, ToolDeps } from "../shared/agent/tool.helpers.js";
import { error, success } from "../shared/agent/tool.helpers.js";
import type { QuestionMode } from "../shared/schemas/question.schema.js";

/**
 * Detection modes whose questions derive solely from the caller's own data
 * (profile gaps, own intents, own discovery sessions). Negotiation-mode
 * questions are excluded for network-scoped agents: their prompts are seeded
 * from opportunity metadata that can reference out-of-scope networks and
 * other users' content (same leak class as the getOpportunitiesForUser fix).
 */
const SELF_OWNED_MODES: QuestionMode[] = ["profile", "intent", "discovery"];

/**
 * Creates MCP tool definitions for the questioner domain.
 * Exposes `read_pending_questions` for retrieving the caller's pending
 * questions generated by QuestionerAgent (profile, intent, negotiation, discovery modes).
 *
 * Network-scoped agent keys (context.networkId set via applyNetworkScopeToContext)
 * are clamped to self-owned modes; the result then carries a `scopeRestriction`
 * block mirroring the network-tools convention.
 *
 * @param defineTool - Tool factory provided by the composition root.
 * @param deps       - Shared tool dependencies; `findPendingQuestions` is optional
 *                     and the tool fails gracefully when absent.
 */
export function createQuestionerTools(defineTool: DefineTool, deps: ToolDeps) {
  const readPendingQuestions = defineTool({
    name: "read_pending_questions",
    description:
      "Returns pending questions generated for the authenticated user across all modes " +
      "(profile, intent, negotiation, discovery). These are questions generated by the " +
      "system to help surface missing signals, refine intents, or capture engagement context.\n\n" +
      "**Returns:** List of pending questions, each with `id`, `title`, `prompt`, `options`, " +
      "`multiSelect`, `mode`, `sourceType`, `sourceId`, `createdAt`, and optional `expiresAt`. " +
      "Network-scoped agents receive only profile/intent/discovery questions plus a " +
      "`scopeRestriction` note.\n\n" +
      "**Use:** Call with no arguments to get all pending questions, or pass `limit` to cap the " +
      "count. For the daily brief the script calls with a small `limit` and renders the first " +
      "question that has not been delivered yet.",
    querySchema: z.object({
      limit: z
        .number()
        .int()
        .min(1)
        .max(10)
        .optional()
        .describe("Maximum number of questions to return (1-10, default 10)."),
    }),
    handler: async ({ context, query }) => {
      if (!deps.findPendingQuestions) {
        return error("Question lookup is not available.");
      }

      const limit = query.limit ?? 10;
      // Scoped-key discriminator: applyNetworkScopeToContext sets networkId
      // only for network-scoped agent keys (mcp.server.ts:558).
      const isScoped = Boolean(context.networkId);

      try {
        const fetched = await deps.findPendingQuestions(context.userId, {
          ...(isScoped ? { modes: SELF_OWNED_MODES } : {}),
          limit,
        });
        // Defense-in-depth: hosts apply `modes`/`limit` SQL-side; re-apply both
        // here so the clamp holds even when a custom dep ignores the filters.
        const visible = isScoped
          ? fetched.filter((q) => (SELF_OWNED_MODES as string[]).includes(q.mode))
          : fetched;
        const limited = visible.slice(0, limit);

        if (isScoped) {
          return success({
            questions: limited,
            scopeRestriction: {
              isScoped: true,
              scopedToIndex: context.indexName ?? context.networkId,
              message:
                `Results exclude negotiation questions because this agent is scoped to ` +
                `"${context.indexName ?? "this index"}".`,
            },
          });
        }

        return success({ questions: limited });
      } catch (err) {
        deps.reportToolError?.(err, {
          operation: "read-pending-questions",
          toolName: "read_pending_questions",
          userId: context.userId,
        });
        return error("Failed to read pending questions.");
      }
    },
  });

  return [readPendingQuestions] as const;
}
