#!/usr/bin/env bun
/**
 * Vendor the mac Workbench UI into the web app's /web route.
 *
 * apps/mac renders its screens as classic <script type="text/babel"> tags that
 * share one scope; apps/web is a Vite SPA where every file is a module. Rather
 * than rewrite 8k lines of working UI into modules — and then maintain two
 * copies of it — this concatenates the same files, in the same order the mac
 * shell loads them, into one generated module. Shared scope is preserved, so
 * the screens stay byte-for-byte what apps/mac runs.
 *
 * Two things differ from the mac bundle, both of them the host's job:
 *   - ui/bridge.jsx is skipped. The web route installs its own window.IndexApp
 *     (app/web/bridge.web.mjs) over fetch + the site's JWT, where the mac one
 *     speaks to Swift over WKWebView message handlers.
 *   - app.jsx's closing ReactDOM.createRoot call renders into a local shim, so
 *     React Router owns the tree and the route renders the exported <App/>.
 *
 * Railway only rebuilds the web service for changes under apps/web (see
 * apps/web/railway.toml), so everything the route needs is copied in rather
 * than imported across apps.
 *
 *   bun run build:workbench-web
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MAC = join(ROOT, "apps/mac");
const OUT = join(ROOT, "apps/web/src/app/web");

/** The bridge is host-specific: the web route ships its own. */
const HOST_OWNED = new Set(["ui/bridge.jsx"]);

/** Order is load order in apps/mac/src/index.html; a file must precede its users. */
function uiSources(): string[] {
  const html = readFileSync(join(MAC, "src/index.html"), "utf8");
  const tags = [...html.matchAll(/<script\s+type="text\/babel"\s+src="([^"]+)"><\/script>/g)];
  if (!tags.length) throw new Error("no text/babel script tags in apps/mac/src/index.html");
  return tags.map((m) => m[1]).filter((src) => !HOST_OWNED.has(src));
}

function banner(command: string): string {
  return `// GENERATED by scripts/${command} — do not edit.\n`;
}

function buildBundle(sources: string[]): string {
  const parts = sources.map((src) => {
    const code = readFileSync(join(MAC, "src", src), "utf8");
    return `// ─── apps/mac/src/${src} ${"─".repeat(Math.max(0, 60 - src.length))}\n${code}`;
  });

  return [
    banner("build-workbench-web.ts"),
    "// Source: apps/mac/src/ui/**, concatenated in apps/mac/src/index.html order",
    "// so the screens keep the single shared scope the mac shell gives them.",
    "/* eslint-disable */",
    "",
    'import * as React from "react";',
    "",
    "// The mac shell owns a page whose #root it mounts into. Here React Router",
    "// owns the tree, so app.jsx's closing createRoot call lands in this shim and",
    "// the route renders the exported <App/> instead.",
    "const ReactDOM = { createRoot: () => ({ render() {}, unmount() {} }) };",
    "",
    ...parts,
    "",
    "export { App };",
    "export default App;",
    "",
  ].join("\n");
}

function copyInto(dir: string, files: { from: string; to: string }[]) {
  mkdirSync(dir, { recursive: true });
  for (const file of files) copyFileSync(file.from, join(dir, file.to));
}

const sources = uiSources();
mkdirSync(OUT, { recursive: true });
writeFileSync(join(OUT, "workbench.generated.jsx"), buildBundle(sources));

// The API client + mappers keep their real ESM imports here — Vite resolves
// them, so unlike the mac bundle (assemble.py strips imports and flattens into
// one IIFE) these are copied verbatim and imported as modules by the bridge.
const apiFiles = readdirSync(join(MAC, "api")).filter((f) => f.endsWith(".mjs"));
copyInto(join(OUT, "api"), apiFiles.map((f) => ({ from: join(MAC, "api", f), to: f })));
writeFileSync(
  join(OUT, "api/README.md"),
  `${banner("build-workbench-web.ts")}\nVendored copy of apps/mac/api. Edit the originals, then re-run \`bun run build:workbench-web\`.\n`,
);

// Styles and the assets they reference. assemble.py inlines these as data URIs
// for the offline WKWebView bundle; Vite fingerprints them instead.
copyInto(join(OUT, "assets"), [{ from: join(MAC, "src/styles/amiga.css"), to: "amiga.css" }]);
copyInto(join(OUT, "assets/fonts"), readdirSync(join(MAC, "src/fonts")).map((f) => ({
  from: join(MAC, "src/fonts", f),
  to: f,
})));
copyInto(join(OUT, "assets/img"), [{ from: join(MAC, "src/img/loading2.gif"), to: "loading2.gif" }]);

const bundleSize = readFileSync(join(OUT, "workbench.generated.jsx")).length;
console.log(
  `wrote apps/web/src/app/web/workbench.generated.jsx (${sources.length} screens, ` +
  `${(bundleSize / 1024).toFixed(0)} KB) + api/, assets/`,
);
