import { mkdir } from 'node:fs/promises';

import { buildNegotiationSystemPrompt, MATCH_INSTRUCTIONS, PRINCIPAL_INBOX_INSTRUCTIONS } from '../packages/agent/src/prompts/agent.prompt.ts';

const directory = new URL('../packages/hermes-plugin/skills/personal-agent/', import.meta.url);
const adapt = (text: string) => text
  .replaceAll('request_principal_input', 'index_request_principal_input')
  .replaceAll('review_principal_inbox', 'index_review_principal_inbox')
  .replace('Take at most one recorded turn each time the host runs you.', 'Take at most one recorded turn per match work ID. A sweep contains several separate match decisions.')
  .replace('stop and summarize the tool result honestly.', 'end that match decision and summarize the tool result honestly. Other matches may continue.');
const content = `---
name: personal-agent
description: Run the selected Index personal agent across its owner's active intents and review its private human inbox.
---

<!-- Generated by bun scripts/generate-hermes-instructions.ts. Edit the canonical agent prompts or this generator. -->

Use these instructions only for Index personal-agent work. Hermes owns reasoning,
its configured model, and the tool loop. Keep each match decision separate from
the human inbox review. Internal summaries are never human delivery.

Start a scheduled sweep with index_list_negotiations. The rotating batch covers
all of the owner's active intents over successive sweeps, including intents with
no matches but pending human messages. For each
actionable match, call index_read_negotiation and use the returned work ID for
exactly one submission or input request. A waiting match does not block others.
Decide each match before reading the next; work IDs cannot be used in inbox review.
Read the inbox with index_read_principal_inbox, then record one review decision.
After replying to owner input, re-read the inbox to consider queued questions.
Reload current context when a work ID is stale; never reuse an older decision.

The tools supply the principal identity, intent, confirmed profile, private
conversation, context revision, observed negotiations, and protocol guidance.
Only that confirmed context establishes facts. Use actual calendar dates for
agreed dates. An A2A agreement is a recommendation pending separate human review;
it does not establish that a connection, meeting, payment, or work occurred.
Owner input is captured by the native gateway hook. Never write an answer through
a tool. A reply to a displayed question retains its question ID and exact scope;
internal reconsideration notes remain advice, not new principal evidence.

## Standing policy

${adapt(buildNegotiationSystemPrompt({ guidance: 'Use protocol.guidance from the current negotiation response.', principalContext: 'Use the current tool-provided confirmed principal context.' }))}

## Match decision

${adapt(MATCH_INSTRUCTIONS)}

## Human inbox review

${adapt(PRINCIPAL_INBOX_INSTRUCTIONS)}
`;

const target = new URL('SKILL.md', directory);
if (process.argv.includes('--check')) {
  if (await Bun.file(target).text() !== content) throw new Error('Hermes instructions are stale; run bun scripts/generate-hermes-instructions.ts');
} else {
  await mkdir(directory, { recursive: true });
  await Bun.write(target, content);
}
