#!/usr/bin/env bash
# Split protected macOS release transaction: prepare(no authority), authorize(GH),
# candidate(Apple), publish(GH). Never combine GitHub and Apple credentials.
set -euo pipefail
set +x
umask 077
readonly RELEASE_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
readonly MAC_DIRECTORY="$(cd "$RELEASE_DIRECTORY/.." && pwd -P)"
readonly REPO_ROOT="$(cd "$MAC_DIRECTORY/../.." && pwd -P)"
readonly CHECKOUT_DIST_DIRECTORY="$MAC_DIRECTORY/dist"
readonly FINAL_DIRECTORY="$CHECKOUT_DIST_DIRECTORY/final"
readonly METADATA_DIRECTORY="$CHECKOUT_DIST_DIRECTORY/release"
readonly RELEASE_WORK_ROOT="${INDEX_RELEASE_WORK_ROOT:-}"
readonly ARTIFACT_DIRECTORY="$RELEASE_WORK_ROOT/artifacts"
readonly PREPARE_DIRECTORY="$ARTIFACT_DIRECTORY/unsigned"
readonly CANDIDATE_DIRECTORY="$ARTIFACT_DIRECTORY/candidate"
readonly AUTHORITY_DIRECTORY="$RELEASE_WORK_ROOT/authority"
readonly STATE_DIRECTORY="$AUTHORITY_DIRECTORY/state"
readonly HANDOFF_MANIFEST="$AUTHORITY_DIRECTORY/prepare.seal.tsv"
readonly AUTHORIZATION_MARKER="$STATE_DIRECTORY/authorization.sha256"
readonly PUBLICATION_MANIFEST="$AUTHORITY_DIRECTORY/publication.seal.tsv"
readonly ATTESTATION_MARKER="$STATE_DIRECTORY/attestation.complete"
readonly MAX_RELEASE_PAGES=100
readonly VERSION=1.0.0 TAG=v1.0.0 APP_DMG=Index-macOS-1.0.0-universal.dmg CONNECTOR_DMG=IndexConnector-1.0.0-universal.dmg
readonly PUBLICATION_FILES=("$APP_DMG" "$CONNECTOR_DMG" macos-release.json macos-release.cms SHA256SUMS)
readonly APPLE_SECRET_NAMES=(INDEX_DEVELOPER_ID_CERTIFICATE_P12 INDEX_DEVELOPER_ID_CERTIFICATE_PASSWORD INDEX_APP_PROVISIONING_PROFILE_BASE64 INDEX_CONNECTOR_PROVISIONING_PROFILE_BASE64 INDEX_NOTARY_API_KEY_BASE64 INDEX_NOTARY_KEY_ID INDEX_NOTARY_ISSUER_ID)
TRANSACTION_ROOT="" TEMPORARY_KEYCHAIN="" TEMPORARY_KEYCHAIN_PASSWORD="" APP_PROFILE_PATH="" CONNECTOR_PROFILE_PATH="" NOTARY_PROFILE_PATH="" CREATED_RELEASE_ID="" DRAFT_PUBLISHED=0
release_error(){ printf 'production release refused: %s\n' "$1" >&2;return 1;}; run_credential_free_build(){ local n;local -a clean=(-u GH_TOKEN -u GITHUB_TOKEN);for n in "${APPLE_SECRET_NAMES[@]}";do clean+=(-u "$n");done;env "${clean[@]}" "$@";}; run_precredential_phases(){ validate_release_host;run_credential_free_build "$@";validate_release_host;install_protected_credentials;}; require_value(){ [[ -n "${!1:-}" ]]||release_error "$1 is required";}; require_tool(){ command -v "$1" >/dev/null||release_error "$1 is required";}; sha256_file(){ shasum -a 256 "$1"|awk '{print $1}';}
assert_secret_environment_absent(){ local n;[[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]||release_error "GitHub authority is forbidden";for n in "${APPLE_SECRET_NAMES[@]}";do [[ -z "${!n:-}" ]]||release_error "Apple secret environment is forbidden";done;}
assert_apple_only_environment(){ local n;[[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]||release_error "GitHub authority is forbidden in candidate phase";for n in "${APPLE_SECRET_NAMES[@]}";do require_value "$n";done;}
assert_github_only_environment(){ require_value GH_TOKEN;local n;for n in "${APPLE_SECRET_NAMES[@]}";do [[ -z "${!n:-}" ]]||release_error "Apple authority is forbidden in GitHub phase";done;}
validate_inputs(){ local n;for n in GITHUB_ACTIONS GITHUB_REPOSITORY GITHUB_SHA GITHUB_RUN_ID GITHUB_RUN_ATTEMPT RUNNER_ENVIRONMENT RUNNER_TEMP INDEX_RELEASE_WORK_ROOT INDEX_RELEASE_TAG INDEX_RELEASE_COMMIT INDEX_BUILD_NUMBER INDEX_RELEASE_MACOS_VERSION INDEX_RELEASE_MACOS_BUILD INDEX_RELEASE_EXPECTED_RUNNER_IMAGE INDEX_RELEASE_EXPECTED_RUNNER_VERSION INDEX_RELEASE_CMS_IDENTITY_HASH INDEX_RELEASE_CMS_CERT_SHA256 INDEX_RELEASE_TAG_RULESET_ID INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256 INDEX_RELEASE_RUNNER_LISTENER_PATH INDEX_RELEASE_RUNNER_LISTENER_SHA256 INDEX_RELEASE_RUNNER_WORKER_PATH INDEX_RELEASE_RUNNER_WORKER_SHA256;do require_value "$n";done;[[ "$GITHUB_ACTIONS" == true&&"$RUNNER_ENVIRONMENT" == github-hosted&&"$INDEX_RELEASE_TAG" == "$TAG"&&"$INDEX_RELEASE_COMMIT" == "$GITHUB_SHA"&&"$INDEX_RELEASE_COMMIT" =~ ^[0-9a-f]{40}$&&"$INDEX_BUILD_NUMBER" =~ ^[1-9][0-9]*$ ]]||release_error "workflow identity is invalid";[[ "$INDEX_RELEASE_CMS_IDENTITY_HASH" =~ ^[0-9a-f]{40}$&&"$INDEX_RELEASE_CMS_CERT_SHA256" =~ ^[0-9a-f]{64}$&&"$INDEX_RELEASE_TAG_RULESET_ID" =~ ^[1-9][0-9]*$&&"$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256" =~ ^[0-9a-f]{64}$ ]]||release_error "reviewed pins are invalid";local expected_root="$RUNNER_TEMP/index-production-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}";[[ "$RELEASE_WORK_ROOT" == "$expected_root"&&"$RELEASE_WORK_ROOT" != "$REPO_ROOT"/* ]]||release_error "release work root is not the reviewed runner-temp path";}
validate_release_host(){ [[ "$(sw_vers -productVersion)" == "$INDEX_RELEASE_MACOS_VERSION"&&"$(sw_vers -buildVersion)" == "$INDEX_RELEASE_MACOS_BUILD"&&"${ImageOS:-}" == "$INDEX_RELEASE_EXPECTED_RUNNER_IMAGE"&&"${ImageVersion:-}" == "$INDEX_RELEASE_EXPECTED_RUNNER_VERSION" ]]||release_error "actual host differs from reviewed pins";}
cleanup_checkout_outputs(){ rm -rf -- "$CHECKOUT_DIST_DIRECTORY";}
validate_source_checkout(){ git -C "$REPO_ROOT" diff-index --quiet "$INDEX_RELEASE_COMMIT" --||release_error "tracked checkout changed";[[ -z "$(git -C "$REPO_ROOT" status --porcelain=v1 --untracked-files=all)" ]]||release_error "checkout contains unapproved untracked files";}
validate_local_tagged_checkout(){ validate_source_checkout;[[ "$(git -C "$REPO_ROOT" rev-parse HEAD)" == "$INDEX_RELEASE_COMMIT"&&"$(git -C "$REPO_ROOT" cat-file -t "refs/tags/$INDEX_RELEASE_TAG")" == tag&&"$(git -C "$REPO_ROOT" rev-parse "refs/tags/$INDEX_RELEASE_TAG^{commit}")" == "$INDEX_RELEASE_COMMIT" ]]||release_error "local annotated tag provenance failed";}
validate_ruleset_json(){ bun "$RELEASE_DIRECTORY/verify-tag-ruleset.mjs" "$1" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_TAG_RULESET_ID"||release_error "reviewed ruleset is not immutable and bypass-free";}
validate_remote_annotated_tag(){ local direct peeled ruleset;direct="$(git -C "$REPO_ROOT" ls-remote --refs origin "refs/tags/$INDEX_RELEASE_TAG"|awk '{print $1;c++}END{if(c!=1)exit 1}')"||release_error "remote tag object missing";peeled="$(git -C "$REPO_ROOT" ls-remote origin "refs/tags/$INDEX_RELEASE_TAG^{}"|awk '{print $1;c++}END{if(c!=1)exit 1}')"||release_error "remote peeled tag missing";[[ "$direct" == "$(git -C "$REPO_ROOT" rev-parse "refs/tags/$INDEX_RELEASE_TAG")"&&"$peeled" == "$INDEX_RELEASE_COMMIT" ]]||release_error "remote tag drift";ruleset="$(gh api "/repos/${GITHUB_REPOSITORY}/rulesets/${INDEX_RELEASE_TAG_RULESET_ID}")"||release_error "ruleset unavailable";validate_ruleset_json "$ruleset";}
validate_tagged_provenance(){ validate_local_tagged_checkout;validate_remote_annotated_tag;}
write_process_allowlist(){ cat >"$1" <<'EOF'
/sbin/launchd
/usr/libexec/UserEventAgent
/usr/sbin/distnoted
EOF
[[ "$(sha256_file "$1")" == "$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256" ]]||release_error "process allowlist pin mismatch";}
assert_no_unrelated_same_uid_processes(){ [[ -z "$(jobs -pr)" ]]||release_error "background jobs forbidden";local allow="$STATE_DIRECTORY/process.allow";[[ -f "$allow" ]]||release_error "sealed process allowlist missing";python3 "$RELEASE_DIRECTORY/process-isolation.py" --root-pid "$$" --uid "$(id -u)" --allowlist "$allow" --allowlist-sha256 "$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256" --listener-path "$INDEX_RELEASE_RUNNER_LISTENER_PATH" --listener-sha256 "$INDEX_RELEASE_RUNNER_LISTENER_SHA256" --worker-path "$INDEX_RELEASE_RUNNER_WORKER_PATH" --worker-sha256 "$INDEX_RELEASE_RUNNER_WORKER_SHA256";}
seal_paths(){ local out="$1" root="$2";python3 "$RELEASE_DIRECTORY/sealed-inventory.py" create "$root" "$out";}
verify_seal(){ python3 "$RELEASE_DIRECTORY/sealed-inventory.py" verify "$1" "$2"||release_error "sealed handoff changed";}
verify_prepare_seal(){ verify_seal "$PREPARE_DIRECTORY" "$HANDOFF_MANIFEST";}
verify_authorization_seal(){ [[ "$(sed -n 1p "$AUTHORIZATION_MARKER")" == "$(sha256_file "$HANDOFF_MANIFEST")" ]]||release_error "authorization seal changed";verify_prepare_seal;}
verify_candidate_seal(){ verify_seal "$CANDIDATE_DIRECTORY" "$PUBLICATION_MANIFEST";}
copy_tree_noreplace(){ local source="$1" destination="$2";[[ ! -e "$destination"&&! -L "$destination" ]]||release_error "handoff destination already exists";mkdir -m 700 "$destination";cp -R "$source"/. "$destination"/;}
externalize_prepare_handoff(){ local source="$1" destination="$2" seal="$3";copy_tree_noreplace "$source" "$destination";cleanup_checkout_outputs;validate_source_checkout;seal_paths "$seal" "$destination";}
assemble_candidate(){ [[ ! -e "$CANDIDATE_DIRECTORY"&&! -L "$CANDIDATE_DIRECTORY" ]]||release_error "candidate handoff already exists";mkdir -m 700 "$CANDIDATE_DIRECTORY";cp "$FINAL_DIRECTORY/$APP_DMG" "$CANDIDATE_DIRECTORY/$APP_DMG";cp "$FINAL_DIRECTORY/$CONNECTOR_DMG" "$CANDIDATE_DIRECTORY/$CONNECTOR_DMG";cp "$METADATA_DIRECTORY/macos-release.json" "$METADATA_DIRECTORY/macos-release.cms" "$METADATA_DIRECTORY/SHA256SUMS" "$CANDIDATE_DIRECTORY/";chmod 600 "$CANDIDATE_DIRECTORY"/*;}
assert_release_absent(){ local releases;releases="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/releases?per_page=100" --jq '.[]|[.id,.tag_name]|@tsv')"||release_error "release absence unavailable";! awk -F'\t' -v t="$INDEX_RELEASE_TAG" '$2==t{found=1}END{exit !found}'<<<"$releases"||release_error "release already exists";}
validate_monotonic_release(){
  local dir data record parsed tag_encoded target_encoded tag target_commit draft prerelease njson ncms napp nconnector nsums extra metadata cms
  dir="$(mktemp -d "$STATE_DIRECTORY/prior.XXXXXX")"
  data="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/releases?per_page=100" --jq '.[]|@base64')"||release_error "prior inventory unavailable"
  [[ -n "$data" ]]||return 0
  while IFS= read -r record;do
    [[ "$record" =~ ^[A-Za-z0-9+/]*={0,2}$ ]]||release_error "historical release record encoding is invalid"
    parsed="$(printf '%s' "$record"|base64 --decode|bun -e '
const r=JSON.parse(await Bun.stdin.text());
if(!r||typeof r!=="object"||Array.isArray(r)||typeof r.tag_name!=="string"||typeof r.draft!=="boolean"||typeof r.prerelease!=="boolean"||!Array.isArray(r.assets)||r.assets.some(a=>!a||typeof a!=="object"||typeof a.name!=="string"))process.exit(1);
const names=r.assets.map(a=>a.name), count=p=>names.filter(p).length, enc=s=>Buffer.from(s).toString("base64");
const macEvidence=names.some(n=>n==="macos-release.json"||n==="macos-release.cms"||n==="SHA256SUMS"||/^Index-macOS-.*-universal\.dmg$/.test(n)||/^IndexConnector-.*-universal\.dmg$/.test(n));
if(macEvidence&&!/^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)(?![\s\S])/.test(r.tag_name))process.exit(1);
if(macEvidence&&!(typeof r.target_commitish==="string"&&/^[0-9a-f]{40}$/.test(r.target_commitish)))process.exit(1);
console.log([enc(r.tag_name),enc(typeof r.target_commitish==="string"?r.target_commitish:""),r.draft,r.prerelease,count(n=>n==="macos-release.json"),count(n=>n==="macos-release.cms"),count(n=>/^Index-macOS-.*-universal\.dmg$/.test(n)),count(n=>/^IndexConnector-.*-universal\.dmg$/.test(n)),count(n=>n==="SHA256SUMS")].join("|"));
')"||release_error "historical release record is malformed"
    IFS='|' read -r tag_encoded target_encoded draft prerelease njson ncms napp nconnector nsums extra<<<"$parsed"
    [[ -z "${extra:-}"&&"$draft" =~ ^(true|false)$&&"$prerelease" =~ ^(true|false)$&&"$njson" =~ ^[0-9]+$&&"$ncms" =~ ^[0-9]+$&&"$napp" =~ ^[0-9]+$&&"$nconnector" =~ ^[0-9]+$&&"$nsums" =~ ^[0-9]+$ ]]||release_error "historical release record fields are malformed"
    tag="$(printf '%s' "$tag_encoded"|base64 --decode)"||release_error "historical release tag encoding is invalid"
    target_commit="$(printf '%s' "$target_encoded"|base64 --decode)"||release_error "historical release target encoding is invalid"
    ((njson+ncms+napp+nconnector+nsums==0))&&continue
    [[ "$target_commit" =~ ^[0-9a-f]{40}$ ]]||release_error "historical release target commit is noncanonical"
    [[ "$tag" =~ ^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$ ]]||release_error "historical macOS release tag is noncanonical"
    [[ "$draft" == false&&"$prerelease" == false ]]||continue
    ((njson==1&&ncms==1&&napp==1&&nconnector==1&&nsums==1))||release_error "historical macOS release has incomplete or duplicate full asset set"
    local release_index="${metadata_index:-0}";metadata_index=$((release_index+1));metadata="$dir/$release_index.json";cms="$dir/$release_index.cms";mkdir -m 700 "$dir/$release_index.files"
    gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern macos-release.json --output "$metadata">/dev/null
    gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern macos-release.cms --output "$cms">/dev/null
    gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern 'Index*-universal.dmg' --dir "$dir/$release_index.files">/dev/null
    gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern SHA256SUMS --output "$dir/$release_index.sums">/dev/null
    bash "$RELEASE_DIRECTORY/verify-prior-release-metadata.sh" "$metadata" "$cms" "$dir/$release_index.files" "$dir/$release_index.sums" "$tag" "$GITHUB_REPOSITORY" "$target_commit"
    bun -e 'const p=JSON.parse(await Bun.file(process.argv[1]).text()),a=p.releaseVersion.split(".").map(BigInt),b=process.argv[2].split(".").map(BigInt);const newer=b[0]>a[0]||(b[0]===a[0]&&(b[1]>a[1]||(b[1]===a[1]&&b[2]>a[2])));if(!newer||BigInt(process.argv[3])<=BigInt(p.buildNumber))process.exit(1)' "$metadata" "$VERSION" "$INDEX_BUILD_NUMBER"||release_error "non-monotonic release"
  done<<<"$data"
}
release_cleanup(){ local s=$?;set +e;set +x;if ((s!=0))&&[[ -n "$CREATED_RELEASE_ID"&&"$DRAFT_PUBLISHED" == 0&&-n "${GH_TOKEN:-}" ]];then cleanup_created_release>/dev/null 2>&1||printf 'private draft requires operator cleanup by numeric ID %s\n' "$CREATED_RELEASE_ID" >&2;fi;[[ -n "$TEMPORARY_KEYCHAIN" ]]&&security delete-keychain "$TEMPORARY_KEYCHAIN">/dev/null 2>&1;[[ -n "$APP_PROFILE_PATH" ]]&&rm -f "$APP_PROFILE_PATH";[[ -n "$CONNECTOR_PROFILE_PATH" ]]&&rm -f "$CONNECTOR_PROFILE_PATH";[[ -n "$NOTARY_PROFILE_PATH" ]]&&rm -f "$NOTARY_PROFILE_PATH";[[ -n "$TRANSACTION_ROOT" ]]&&rm -rf "$TRANSACTION_ROOT";TEMPORARY_KEYCHAIN="";APP_PROFILE_PATH="";CONNECTOR_PROFILE_PATH="";NOTARY_PROFILE_PATH="";TRANSACTION_ROOT="";unset "${APPLE_SECRET_NAMES[@]}";exit "$s";};trap release_cleanup EXIT
decode_secret_file(){ (umask 077;printf %s "${!1}"|base64 --decode>"$2")2>/dev/null;chmod 600 "$2";}
resolve_identity_label(){ local listing matches;listing="$(security find-identity -v -p codesigning "$TEMPORARY_KEYCHAIN" 2>/dev/null)";matches="$(awk -v h="$INDEX_RELEASE_CMS_IDENTITY_HASH" '{if(tolower($2)==h&&match($0,/"Developer ID Application:[^"]+"/))print substr($0,RSTART+1,RLENGTH-2)}'<<<"$listing")";[[ "$(grep -c .<<<"$matches")" == 1 ]]||release_error "identity pin not unique";CODESIGN_IDENTITY="$matches";export CODESIGN_IDENTITY;}
install_protected_credentials(){ TRANSACTION_ROOT="$(mktemp -d "$RUNNER_TEMP/index-apple.XXXXXX")";chmod 700 "$TRANSACTION_ROOT";TEMPORARY_KEYCHAIN="$TRANSACTION_ROOT/release.keychain-db";TEMPORARY_KEYCHAIN_PASSWORD="$(openssl rand -hex 32)";APP_PROFILE_PATH="$TRANSACTION_ROOT/app.provisionprofile";CONNECTOR_PROFILE_PATH="$TRANSACTION_ROOT/connector.provisionprofile";local p12="$TRANSACTION_ROOT/id.p12" key="$TRANSACTION_ROOT/notary.p8";decode_secret_file INDEX_DEVELOPER_ID_CERTIFICATE_P12 "$p12";decode_secret_file INDEX_APP_PROVISIONING_PROFILE_BASE64 "$APP_PROFILE_PATH";decode_secret_file INDEX_CONNECTOR_PROVISIONING_PROFILE_BASE64 "$CONNECTOR_PROFILE_PATH";decode_secret_file INDEX_NOTARY_API_KEY_BASE64 "$key";security create-keychain -p "$TEMPORARY_KEYCHAIN_PASSWORD" "$TEMPORARY_KEYCHAIN">/dev/null;security set-keychain-settings -lut 21600 "$TEMPORARY_KEYCHAIN">/dev/null;security unlock-keychain -p "$TEMPORARY_KEYCHAIN_PASSWORD" "$TEMPORARY_KEYCHAIN">/dev/null;security import "$p12" -k "$TEMPORARY_KEYCHAIN" -P "$INDEX_DEVELOPER_ID_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security>/dev/null;security set-key-partition-list -S apple-tool:,apple: -s -k "$TEMPORARY_KEYCHAIN_PASSWORD" "$TEMPORARY_KEYCHAIN">/dev/null;security list-keychains -d user -s "$TEMPORARY_KEYCHAIN" /Library/Keychains/System.keychain>/dev/null;resolve_identity_label;NOTARYTOOL_PROFILE="index-production-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}";xcrun notarytool store-credentials "$NOTARYTOOL_PROFILE" --key "$key" --key-id "$INDEX_NOTARY_KEY_ID" --issuer "$INDEX_NOTARY_ISSUER_ID" --keychain "$TEMPORARY_KEYCHAIN">/dev/null;export INDEX_APP_PROVISIONING_PROFILE="$APP_PROFILE_PATH" INDEX_CONNECTOR_PROVISIONING_PROFILE="$CONNECTOR_PROFILE_PATH" NOTARYTOOL_PROFILE;rm -f "$p12" "$key";}
verify_final_artifact_evidence(){ local n a e d;for n in "$APP_DMG" "$CONNECTOR_DMG";do a="$FINAL_DIRECTORY/$n";e="$a.reproducibility.txt";d="$(awk -F= '$1=="finalArtifact.sha256"{v=$2;c++}END{if(c==1)print v}' "$e")";[[ "$d" =~ ^[0-9a-f]{64}$&&"$(sha256_file "$a")" == "$d" ]]||release_error "final artifact evidence mismatch";done;}
prepare_release(){ assert_secret_environment_absent;validate_inputs;validate_release_host;[[ ! -e "$RELEASE_WORK_ROOT"&&! -L "$RELEASE_WORK_ROOT" ]]||release_error "release work root already exists";mkdir -m 700 "$RELEASE_WORK_ROOT" "$ARTIFACT_DIRECTORY" "$AUTHORITY_DIRECTORY" "$STATE_DIRECTORY";cleanup_checkout_outputs;validate_local_tagged_checkout;write_process_allowlist "$STATE_DIRECTORY/process.allow";assert_no_unrelated_same_uid_processes;env -u GH_TOKEN -u GITHUB_TOKEN bash "$RELEASE_DIRECTORY/build-universal.sh";externalize_prepare_handoff "$CHECKOUT_DIST_DIRECTORY/unsigned" "$PREPARE_DIRECTORY" "$HANDOFF_MANIFEST";}
authorize_release(){ assert_github_only_environment;validate_inputs;cleanup_checkout_outputs;validate_source_checkout;verify_prepare_seal;validate_remote_annotated_tag;assert_release_absent;validate_monotonic_release;printf '%s\n' "$(sha256_file "$HANDOFF_MANIFEST")">"$AUTHORIZATION_MARKER";chmod 600 "$AUTHORIZATION_MARKER";}
candidate_release(){ assert_apple_only_environment;validate_inputs;validate_release_host;cleanup_checkout_outputs;validate_source_checkout;verify_prepare_seal;verify_authorization_seal;assert_no_unrelated_same_uid_processes;copy_tree_noreplace "$PREPARE_DIRECTORY" "$CHECKOUT_DIST_DIRECTORY/unsigned";install_protected_credentials;bash "$RELEASE_DIRECTORY/sign-bundles.sh";bash "$RELEASE_DIRECTORY/verify-signatures.sh" "$CHECKOUT_DIST_DIRECTORY/signed";INDEX_RELEASE_ISOLATION_GUARD="$RELEASE_DIRECTORY/build-release-isolation-guard.sh";export INDEX_RELEASE_ISOLATION_GUARD;bash "$MAC_DIRECTORY/scripts/notarize.sh";verify_final_artifact_evidence;mkdir -m 700 "$METADATA_DIRECTORY";bun "$RELEASE_DIRECTORY/generate-release-metadata.ts" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";bash "$RELEASE_DIRECTORY/sign-release-metadata.sh" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";bash "$RELEASE_DIRECTORY/verify-release-metadata.sh" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";verify_final_artifact_evidence;assemble_candidate;cleanup_checkout_outputs;validate_source_checkout;seal_paths "$PUBLICATION_MANIFEST" "$CANDIDATE_DIRECTORY";}
record_attestation(){ assert_secret_environment_absent;verify_candidate_seal;[[ "$1" == https://github.com/*/attestations/* ]]||release_error "attestation URL invalid";printf '%s\n%s\n' "$(sha256_file "$PUBLICATION_MANIFEST")" "$1">"$ATTESTATION_MARKER";chmod 600 "$ATTESTATION_MARKER";}
release_marker(){ printf 'index-production-run:%s:%s:%s' "$GITHUB_RUN_ID" "$GITHUB_RUN_ATTEMPT" "$INDEX_RELEASE_COMMIT";}
api(){ local method="$1" path="$2";shift 2;gh api --method "$method" "$path" "$@";}
recover_created_draft_id(){ local page=1 response headers body link all='[]';while ((page<=MAX_RELEASE_PAGES));do headers="$(mktemp "$STATE_DIRECTORY/recovery-headers.XXXXXX")";response="$(gh api --method GET -i "/repos/${GITHUB_REPOSITORY}/releases?per_page=100&page=$page")"||{ rm -f "$headers";return 1;};printf '%s' "$response">"$headers";body="$(python3 - "$headers" <<'PY'
import pathlib,sys
raw=pathlib.Path(sys.argv[1]).read_text();parts=raw.replace('\r\n','\n').split('\n\n',1)
if len(parts)!=2:raise SystemExit(1)
print(parts[1],end='')
PY
)"||{ rm -f "$headers";return 1;};all="$(bun -e 'const a=JSON.parse(process.argv[1]),b=JSON.parse(process.argv[2]);if(!Array.isArray(a)||!Array.isArray(b))process.exit(1);console.log(JSON.stringify(a.concat(b)))' "$all" "$body")"||{ rm -f "$headers";return 1;};link="$(tr -d '\r' <"$headers"|awk -F': ' 'tolower($1)=="link"{print substr($0,index($0,": ")+2);c++}END{if(c>1)exit 1}')"||{ rm -f "$headers";return 1;};rm -f "$headers";[[ "$link" == *'rel="next"'* ]]||break;((page++));done;((page<=MAX_RELEASE_PAGES))||return 1;CREATED_RELEASE_ID="$(bun -e 'const rs=JSON.parse(process.argv[1]),m=rs.filter(r=>r.draft===true&&r.tag_name===process.argv[2]&&r.target_commitish===process.argv[3]&&r.body===process.argv[4]);if(m.length!==1){console.error("exactly one matching private draft required");process.exit(1)}console.log(m[0].id)' "$all" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$(release_marker)")";}
cleanup_created_release(){ [[ "$CREATED_RELEASE_ID" =~ ^[1-9][0-9]*$ ]]||return 1;local r;r="$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")"||return 1;bun -e 'const r=JSON.parse(process.argv[1]);if(String(r.id)!==process.argv[2]||r.tag_name!==process.argv[3]||r.target_commitish!==process.argv[4]||r.body!==process.argv[5]||r.draft!==true)process.exit(1)' "$r" "$CREATED_RELEASE_ID" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$(release_marker)"||return 1;api DELETE "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}";}
verify_public_release(){ local r="$1";bun -e 'const r=JSON.parse(process.argv[1]);if(String(r.id)!==process.argv[2]||r.tag_name!==process.argv[3]||r.target_commitish!==process.argv[4]||r.body!==process.argv[5]||r.draft!==false||r.prerelease!==false||!r.published_at)process.exit(1)' "$r" "$CREATED_RELEASE_ID" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$(release_marker)"||release_error "authoritative public release mismatch";verify_uploaded_assets "$r";}
verify_uploaded_assets(){ local supplied="${1:-}"; local r;r="${supplied:-$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")}";bun -e 'const r=JSON.parse(process.argv[1]),m=process.argv.slice(2).map(x=>{const [n,h]=x.split("=");return[n,h]});if(r.assets.length!==m.length)process.exit(1);for(const[n,h]of m){const a=r.assets.filter(x=>x.name===n);if(a.length!==1||a[0].digest!==`sha256:${h}`)process.exit(1)}' "$r" "${UPLOAD_EXPECTED[@]}"||release_error "uploaded assets differ by name/hash";}
upload_approved_candidate(){ local upload_url="$1" relative type mode size h f n;UPLOAD_EXPECTED=();while IFS=$'\t' read -r relative type mode size h;do [[ "$type" == f ]]||release_error "publication parser accepted non-file";f="$CANDIDATE_DIRECTORY/$relative";[[ -f "$f"&&! -L "$f" ]]||release_error "approved publication entry is not a regular file";n="$(basename "$relative")";api POST "$upload_url?name=$n" -H 'Content-Type: application/octet-stream' --input "$f">/dev/null||return 1;UPLOAD_EXPECTED+=("$n=$h");done< <(python3 "$RELEASE_DIRECTORY/sealed-inventory.py" approved "$CANDIDATE_DIRECTORY" "$PUBLICATION_MANIFEST" "${PUBLICATION_FILES[@]}");[[ "${#UPLOAD_EXPECTED[@]}" -eq "${#PUBLICATION_FILES[@]}" ]]||release_error "approved publication inventory incomplete";}
publish_release(){ assert_github_only_environment;validate_inputs;cleanup_checkout_outputs;validate_source_checkout;verify_prepare_seal;verify_authorization_seal;verify_candidate_seal;[[ "$(sed -n 1p "$ATTESTATION_MARKER")" == "$(sha256_file "$PUBLICATION_MANIFEST")" ]]||release_error "attestation binding changed";validate_remote_annotated_tag;assert_release_absent;validate_monotonic_release;assert_no_unrelated_same_uid_processes;local body response upload_url;body="$(release_marker)";set +e;response="$(api POST "/repos/${GITHUB_REPOSITORY}/releases" -f tag_name="$INDEX_RELEASE_TAG" -f target_commitish="$INDEX_RELEASE_COMMIT" -f name="Index for macOS $VERSION" -f body="$body" -F draft=true -F prerelease=false)";local post_status=$?;set -e;CREATED_RELEASE_ID="$(bun -e 'const r=JSON.parse(process.argv[1]);if(!Number.isInteger(r.id)||!r.draft||r.tag_name!==process.argv[2]||r.target_commitish!==process.argv[3]||r.body!==process.argv[4]||typeof r.upload_url!=="string")process.exit(1);console.log(r.id)' "$response" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$body")" 2>/dev/null||{ recover_created_draft_id||release_error "POST response lost and draft recovery ambiguous";response="$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")";};((post_status==0))||[[ -n "$CREATED_RELEASE_ID" ]]||release_error "draft creation failed";upload_url="$(bun -e 'console.log(JSON.parse(process.argv[1]).upload_url.replace(/\{.*$/,""))' "$response")";upload_approved_candidate "$upload_url"||{ cleanup_created_release;return 1;};verify_uploaded_assets;validate_remote_annotated_tag;validate_monotonic_release;assert_no_unrelated_same_uid_processes;local publish_body="$STATE_DIRECTORY/publish.json";printf '%s\n' '{"draft":false}'>"$publish_body";local patched;patched="$(api PATCH "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}" -H 'Content-Type: application/json' --input "$publish_body")"||release_error "public PATCH failed";DRAFT_PUBLISHED=1;verify_public_release "$patched";verify_public_release "$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")";}
if [[ "${BUILD_RELEASE_SOURCE_ONLY:-}" == 1 ]];then trap - EXIT;return 0 2>/dev/null||exit 0;fi
case "${1:-}" in prepare)prepare_release;;authorize)authorize_release;;candidate)candidate_release;;record-attestation)shift;record_attestation "$@";;publish)publish_release;;assert-absence)assert_github_only_environment;assert_release_absent;;*)release_error "usage: prepare|authorize|candidate|record-attestation|publish|assert-absence";;esac
trap - EXIT;release_cleanup 0
