#!/usr/bin/env bash
# Split protected macOS release transaction: prepare(no authority), authorize(GH),
# candidate(Apple), publish(GH). Never combine GitHub and Apple credentials.
set -euo pipefail
set +x
umask 077
readonly RELEASE_DIRECTORY="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
readonly MAC_DIRECTORY="$(cd "$RELEASE_DIRECTORY/.." && pwd -P)"
readonly REPO_ROOT="$(cd "$MAC_DIRECTORY/../.." && pwd -P)"
readonly FINAL_DIRECTORY="$MAC_DIRECTORY/dist/final"
readonly METADATA_DIRECTORY="$MAC_DIRECTORY/dist/release"
readonly STATE_DIRECTORY="$MAC_DIRECTORY/dist/.production-release-state"
readonly HANDOFF_MANIFEST="$STATE_DIRECTORY/prepare.sha256"
readonly AUTHORIZATION_MARKER="$STATE_DIRECTORY/authorization.sha256"
readonly PUBLICATION_MANIFEST="$STATE_DIRECTORY/publication.sha256"
readonly ATTESTATION_MARKER="$STATE_DIRECTORY/attestation.complete"
readonly VERSION=1.0.0 TAG=v1.0.0 APP_DMG=Index-macOS-1.0.0-universal.dmg CONNECTOR_DMG=IndexConnector-1.0.0-universal.dmg
readonly APPLE_SECRET_NAMES=(INDEX_DEVELOPER_ID_CERTIFICATE_P12 INDEX_DEVELOPER_ID_CERTIFICATE_PASSWORD INDEX_APP_PROVISIONING_PROFILE_BASE64 INDEX_CONNECTOR_PROVISIONING_PROFILE_BASE64 INDEX_NOTARY_API_KEY_BASE64 INDEX_NOTARY_KEY_ID INDEX_NOTARY_ISSUER_ID)
TRANSACTION_ROOT="" TEMPORARY_KEYCHAIN="" TEMPORARY_KEYCHAIN_PASSWORD="" APP_PROFILE_PATH="" CONNECTOR_PROFILE_PATH="" NOTARY_PROFILE_PATH="" CREATED_RELEASE_ID="" DRAFT_PUBLISHED=0
release_error(){ printf 'production release refused: %s\n' "$1" >&2;return 1;}; run_credential_free_build(){ local n;local -a clean=(-u GH_TOKEN -u GITHUB_TOKEN);for n in "${APPLE_SECRET_NAMES[@]}";do clean+=(-u "$n");done;env "${clean[@]}" "$@";}; run_precredential_phases(){ validate_release_host;run_credential_free_build "$@";validate_release_host;install_protected_credentials;}; require_value(){ [[ -n "${!1:-}" ]]||release_error "$1 is required";}; require_tool(){ command -v "$1" >/dev/null||release_error "$1 is required";}; sha256_file(){ shasum -a 256 "$1"|awk '{print $1}';}
assert_secret_environment_absent(){ local n;[[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]||release_error "GitHub authority is forbidden";for n in "${APPLE_SECRET_NAMES[@]}";do [[ -z "${!n:-}" ]]||release_error "Apple secret environment is forbidden";done;}
assert_apple_only_environment(){ local n;[[ -z "${GH_TOKEN:-}${GITHUB_TOKEN:-}" ]]||release_error "GitHub authority is forbidden in candidate phase";for n in "${APPLE_SECRET_NAMES[@]}";do require_value "$n";done;}
assert_github_only_environment(){ require_value GH_TOKEN;local n;for n in "${APPLE_SECRET_NAMES[@]}";do [[ -z "${!n:-}" ]]||release_error "Apple authority is forbidden in GitHub phase";done;}
validate_inputs(){ local n;for n in GITHUB_ACTIONS GITHUB_REPOSITORY GITHUB_SHA GITHUB_RUN_ID GITHUB_RUN_ATTEMPT RUNNER_ENVIRONMENT RUNNER_TEMP INDEX_RELEASE_TAG INDEX_RELEASE_COMMIT INDEX_BUILD_NUMBER INDEX_RELEASE_MACOS_VERSION INDEX_RELEASE_MACOS_BUILD INDEX_RELEASE_EXPECTED_RUNNER_IMAGE INDEX_RELEASE_EXPECTED_RUNNER_VERSION INDEX_RELEASE_CMS_IDENTITY_HASH INDEX_RELEASE_CMS_CERT_SHA256 INDEX_RELEASE_TAG_RULESET_ID INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256;do require_value "$n";done;[[ "$GITHUB_ACTIONS" == true&&"$RUNNER_ENVIRONMENT" == github-hosted&&"$INDEX_RELEASE_TAG" == "$TAG"&&"$INDEX_RELEASE_COMMIT" == "$GITHUB_SHA"&&"$INDEX_RELEASE_COMMIT" =~ ^[0-9a-f]{40}$&&"$INDEX_BUILD_NUMBER" =~ ^[1-9][0-9]*$ ]]||release_error "workflow identity is invalid";[[ "$INDEX_RELEASE_CMS_IDENTITY_HASH" =~ ^[0-9a-f]{40}$&&"$INDEX_RELEASE_CMS_CERT_SHA256" =~ ^[0-9a-f]{64}$&&"$INDEX_RELEASE_TAG_RULESET_ID" =~ ^[1-9][0-9]*$&&"$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256" =~ ^[0-9a-f]{64}$ ]]||release_error "reviewed pins are invalid";}
validate_release_host(){ [[ "$(sw_vers -productVersion)" == "$INDEX_RELEASE_MACOS_VERSION"&&"$(sw_vers -buildVersion)" == "$INDEX_RELEASE_MACOS_BUILD"&&"${ImageOS:-}" == "$INDEX_RELEASE_EXPECTED_RUNNER_IMAGE"&&"${ImageVersion:-}" == "$INDEX_RELEASE_EXPECTED_RUNNER_VERSION" ]]||release_error "actual host differs from reviewed pins";}
validate_local_tagged_checkout(){ [[ -z "$(git -C "$REPO_ROOT" status --porcelain=v1 --untracked-files=all)" ]]||release_error "checkout is not clean";[[ "$(git -C "$REPO_ROOT" rev-parse HEAD)" == "$INDEX_RELEASE_COMMIT"&&"$(git -C "$REPO_ROOT" cat-file -t "refs/tags/$INDEX_RELEASE_TAG")" == tag&&"$(git -C "$REPO_ROOT" rev-parse "refs/tags/$INDEX_RELEASE_TAG^{commit}")" == "$INDEX_RELEASE_COMMIT" ]]||release_error "local annotated tag provenance failed";}
validate_ruleset_json(){ bun -e 'const r=JSON.parse(process.argv[1]),tag=process.argv[2],id=process.argv[3];const c=r.conditions?.ref_name;if(String(r.id)!==id||r.enforcement!=="active"||r.target!=="tag"||(r.bypass_actors?.length??0)!==0||!c||!Array.isArray(c.include)||!Array.isArray(c.exclude)||!c.include.some(x=>x===`refs/tags/${tag}`||x==="~ALL")||c.exclude.some(x=>x===`refs/tags/${tag}`||x==="~ALL")||!r.rules?.some(x=>x.type==="update")||!r.rules?.some(x=>x.type==="deletion"))process.exit(1)' "$1" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_TAG_RULESET_ID"||release_error "reviewed ruleset is not immutable and bypass-free";}
validate_remote_annotated_tag(){ local direct peeled ruleset;direct="$(git -C "$REPO_ROOT" ls-remote --refs origin "refs/tags/$INDEX_RELEASE_TAG"|awk '{print $1;c++}END{if(c!=1)exit 1}')"||release_error "remote tag object missing";peeled="$(git -C "$REPO_ROOT" ls-remote origin "refs/tags/$INDEX_RELEASE_TAG^{}"|awk '{print $1;c++}END{if(c!=1)exit 1}')"||release_error "remote peeled tag missing";[[ "$direct" == "$(git -C "$REPO_ROOT" rev-parse "refs/tags/$INDEX_RELEASE_TAG")"&&"$peeled" == "$INDEX_RELEASE_COMMIT" ]]||release_error "remote tag drift";ruleset="$(gh api "/repos/${GITHUB_REPOSITORY}/rulesets/${INDEX_RELEASE_TAG_RULESET_ID}")"||release_error "ruleset unavailable";validate_ruleset_json "$ruleset";}
validate_tagged_provenance(){ validate_local_tagged_checkout;validate_remote_annotated_tag;}
write_process_allowlist(){ cat >"$1" <<'EOF'
/sbin/launchd
/usr/libexec/UserEventAgent
/usr/sbin/distnoted
EOF
[[ "$(sha256_file "$1")" == "$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256" ]]||release_error "process allowlist pin mismatch";}
assert_no_unrelated_same_uid_processes(){ [[ -z "$(jobs -pr)" ]]||release_error "background jobs forbidden";local allow="$STATE_DIRECTORY/process.allow";[[ -f "$allow" ]]||release_error "sealed process allowlist missing";python3 "$RELEASE_DIRECTORY/process-isolation.py" --root-pid "$$" --uid "$(id -u)" --allowlist "$allow" --allowlist-sha256 "$INDEX_RELEASE_PROCESS_ALLOWLIST_SHA256";}
seal_paths(){ local out="$1";shift;: >"$out";local p;for p in "$@";do [[ -e "$p"&&! -L "$p" ]]||release_error "sealed path missing";if [[ -d "$p" ]];then find "$p" -type f -print0|LC_ALL=C sort -z|while IFS= read -r -d '' f;do printf '%s  %s\n' "$(sha256_file "$f")" "${f#$REPO_ROOT/}";done>>"$out";else printf '%s  %s\n' "$(sha256_file "$p")" "${p#$REPO_ROOT/}">>"$out";fi;done;chmod 600 "$out";}
verify_seal(){ local manifest="$1" d p;[[ -f "$manifest"&&! -L "$manifest" ]]||release_error "sealed handoff missing";while read -r d p;do [[ "$d" =~ ^[0-9a-f]{64}$&&-f "$REPO_ROOT/$p"&&! -L "$REPO_ROOT/$p"&&"$(sha256_file "$REPO_ROOT/$p")" == "$d" ]]||release_error "sealed handoff changed";done<"$manifest";}
assert_release_absent(){ local releases;releases="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/releases?per_page=100" --jq '.[]|[.id,.tag_name]|@tsv')"||release_error "release absence unavailable";! awk -F'\t' -v t="$INDEX_RELEASE_TAG" '$2==t{found=1}END{exit !found}'<<<"$releases"||release_error "release already exists";}
validate_monotonic_release(){ local dir data tag draft prerelease assets njson ncms metadata cms;dir="$(mktemp -d "$STATE_DIRECTORY/prior.XXXXXX")";data="$(gh api --paginate "/repos/${GITHUB_REPOSITORY}/releases?per_page=100" --jq '.[]|[.tag_name, .draft, .prerelease,([.assets[].name]|join(","))]|@tsv')"||release_error "prior inventory unavailable";while IFS=$'\t' read -r tag draft prerelease assets;do [[ -n "$tag"&&"$draft" == false&&"$prerelease" == false ]]||continue;njson="$(tr ',' '\n'<<<"$assets"|grep -cx macos-release.json||:)";ncms="$(tr ',' '\n'<<<"$assets"|grep -cx macos-release.cms||:)";((njson==0&&ncms==0))&&continue;((njson==1&&ncms==1))||release_error "duplicate historical macOS asset or incomplete pair";metadata="$dir/$tag.json";cms="$dir/$tag.cms";gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern macos-release.json --output "$metadata">/dev/null;gh release download "$tag" --repo "$GITHUB_REPOSITORY" --pattern macos-release.cms --output "$cms">/dev/null;bash "$RELEASE_DIRECTORY/verify-prior-release-metadata.sh" "$metadata" "$cms";bun -e 'const p=JSON.parse(await Bun.file(process.argv[1]).text()),a=p.releaseVersion.split(".").map(BigInt),b=process.argv[2].split(".").map(BigInt);if(!(b[0]>a[0]||(b[0]===a[0]&&(b[1]>a[1]||(b[1]===a[1]&&b[2]>a[2])))||BigInt(process.argv[3])<=BigInt(p.buildNumber))process.exit(1)' "$metadata" "$VERSION" "$INDEX_BUILD_NUMBER"||release_error "non-monotonic release";done<<<"$data";}
release_cleanup(){ local s=$?;set +e;set +x;if ((s!=0))&&[[ -n "$CREATED_RELEASE_ID"&&"$DRAFT_PUBLISHED" == 0&&-n "${GH_TOKEN:-}" ]];then cleanup_created_release>/dev/null 2>&1||printf 'private draft requires operator cleanup by numeric ID %s\n' "$CREATED_RELEASE_ID" >&2;fi;[[ -n "$TEMPORARY_KEYCHAIN" ]]&&security delete-keychain "$TEMPORARY_KEYCHAIN">/dev/null 2>&1;[[ -n "$APP_PROFILE_PATH" ]]&&rm -f "$APP_PROFILE_PATH";[[ -n "$CONNECTOR_PROFILE_PATH" ]]&&rm -f "$CONNECTOR_PROFILE_PATH";[[ -n "$NOTARY_PROFILE_PATH" ]]&&rm -f "$NOTARY_PROFILE_PATH";[[ -n "$TRANSACTION_ROOT" ]]&&rm -rf "$TRANSACTION_ROOT";TEMPORARY_KEYCHAIN="";APP_PROFILE_PATH="";CONNECTOR_PROFILE_PATH="";NOTARY_PROFILE_PATH="";TRANSACTION_ROOT="";unset "${APPLE_SECRET_NAMES[@]}";exit "$s";};trap release_cleanup EXIT
decode_secret_file(){ (umask 077;printf %s "${!1}"|base64 --decode>"$2")2>/dev/null;chmod 600 "$2";}
resolve_identity_label(){ local listing matches;listing="$(security find-identity -v -p codesigning "$TEMPORARY_KEYCHAIN" 2>/dev/null)";matches="$(awk -v h="$INDEX_RELEASE_CMS_IDENTITY_HASH" '{if(tolower($2)==h&&match($0,/"Developer ID Application:[^"]+"/))print substr($0,RSTART+1,RLENGTH-2)}'<<<"$listing")";[[ "$(grep -c .<<<"$matches")" == 1 ]]||release_error "identity pin not unique";CODESIGN_IDENTITY="$matches";export CODESIGN_IDENTITY;}
install_protected_credentials(){ TRANSACTION_ROOT="$(mktemp -d "$RUNNER_TEMP/index-apple.XXXXXX")";chmod 700 "$TRANSACTION_ROOT";TEMPORARY_KEYCHAIN="$TRANSACTION_ROOT/release.keychain-db";TEMPORARY_KEYCHAIN_PASSWORD="$(openssl rand -hex 32)";APP_PROFILE_PATH="$TRANSACTION_ROOT/app.provisionprofile";CONNECTOR_PROFILE_PATH="$TRANSACTION_ROOT/connector.provisionprofile";local p12="$TRANSACTION_ROOT/id.p12" key="$TRANSACTION_ROOT/notary.p8";decode_secret_file INDEX_DEVELOPER_ID_CERTIFICATE_P12 "$p12";decode_secret_file INDEX_APP_PROVISIONING_PROFILE_BASE64 "$APP_PROFILE_PATH";decode_secret_file INDEX_CONNECTOR_PROVISIONING_PROFILE_BASE64 "$CONNECTOR_PROFILE_PATH";decode_secret_file INDEX_NOTARY_API_KEY_BASE64 "$key";security create-keychain -p "$TEMPORARY_KEYCHAIN_PASSWORD" "$TEMPORARY_KEYCHAIN">/dev/null;security unlock-keychain -p "$TEMPORARY_KEYCHAIN_PASSWORD" "$TEMPORARY_KEYCHAIN">/dev/null;security import "$p12" -k "$TEMPORARY_KEYCHAIN" -P "$INDEX_DEVELOPER_ID_CERTIFICATE_PASSWORD" -T /usr/bin/codesign -T /usr/bin/security>/dev/null;security list-keychains -d user -s "$TEMPORARY_KEYCHAIN" /Library/Keychains/System.keychain>/dev/null;resolve_identity_label;NOTARYTOOL_PROFILE="index-production-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT}";xcrun notarytool store-credentials "$NOTARYTOOL_PROFILE" --key "$key" --key-id "$INDEX_NOTARY_KEY_ID" --issuer "$INDEX_NOTARY_ISSUER_ID" --keychain "$TEMPORARY_KEYCHAIN">/dev/null;export INDEX_APP_PROVISIONING_PROFILE="$APP_PROFILE_PATH" INDEX_CONNECTOR_PROVISIONING_PROFILE="$CONNECTOR_PROFILE_PATH" NOTARYTOOL_PROFILE;rm -f "$p12" "$key";}
verify_final_artifact_evidence(){ local n a e d;for n in "$APP_DMG" "$CONNECTOR_DMG";do a="$FINAL_DIRECTORY/$n";e="$a.reproducibility.txt";d="$(awk -F= '$1=="finalArtifact.sha256"{v=$2;c++}END{if(c==1)print v}' "$e")";[[ "$d" =~ ^[0-9a-f]{64}$&&"$(sha256_file "$a")" == "$d" ]]||release_error "final artifact evidence mismatch";done;}
prepare_release(){ assert_secret_environment_absent;validate_inputs;validate_release_host;validate_local_tagged_checkout;rm -rf "$STATE_DIRECTORY";mkdir -m 700 "$STATE_DIRECTORY";write_process_allowlist "$STATE_DIRECTORY/process.allow";assert_no_unrelated_same_uid_processes;env -u GH_TOKEN -u GITHUB_TOKEN bash "$RELEASE_DIRECTORY/build-universal.sh";seal_paths "$HANDOFF_MANIFEST" "$MAC_DIRECTORY/dist/unsigned" "$STATE_DIRECTORY/process.allow";}
authorize_release(){ assert_github_only_environment;validate_inputs;verify_seal "$HANDOFF_MANIFEST";validate_remote_annotated_tag;assert_release_absent;validate_monotonic_release;seal_paths "$AUTHORIZATION_MARKER" "$HANDOFF_MANIFEST" "$STATE_DIRECTORY/process.allow";}
candidate_release(){ assert_apple_only_environment;validate_inputs;validate_release_host;validate_local_tagged_checkout;verify_seal "$HANDOFF_MANIFEST";verify_seal "$AUTHORIZATION_MARKER";assert_no_unrelated_same_uid_processes;install_protected_credentials;bash "$RELEASE_DIRECTORY/sign-bundles.sh";bash "$RELEASE_DIRECTORY/verify-signatures.sh" "$MAC_DIRECTORY/dist/signed";INDEX_RELEASE_ISOLATION_GUARD="$RELEASE_DIRECTORY/build-release-isolation-guard.sh";export INDEX_RELEASE_ISOLATION_GUARD;bash "$MAC_DIRECTORY/IndexApp/notarize.sh";verify_final_artifact_evidence;mkdir -m 700 "$METADATA_DIRECTORY";bun "$RELEASE_DIRECTORY/generate-release-metadata.ts" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";bash "$RELEASE_DIRECTORY/sign-release-metadata.sh" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";bash "$RELEASE_DIRECTORY/verify-release-metadata.sh" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY" "$INDEX_BUILD_NUMBER" "$INDEX_RELEASE_COMMIT";verify_final_artifact_evidence;seal_paths "$PUBLICATION_MANIFEST" "$FINAL_DIRECTORY" "$METADATA_DIRECTORY";}
record_attestation(){ assert_secret_environment_absent;verify_seal "$PUBLICATION_MANIFEST";[[ "$1" == https://github.com/*/attestations/* ]]||release_error "attestation URL invalid";printf '%s\n%s\n' "$(sha256_file "$PUBLICATION_MANIFEST")" "$1">"$ATTESTATION_MARKER";chmod 600 "$ATTESTATION_MARKER";}
release_marker(){ printf 'index-production-run:%s:%s' "$GITHUB_RUN_ID" "$GITHUB_RUN_ATTEMPT";}
api(){ local method="$1" path="$2";shift 2;gh api --method "$method" "$path" "$@";}
cleanup_created_release(){ [[ "$CREATED_RELEASE_ID" =~ ^[1-9][0-9]*$ ]]||return 1;local r;r="$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")"||return 1;bun -e 'const r=JSON.parse(process.argv[1]);if(String(r.id)!==process.argv[2]||r.tag_name!==process.argv[3]||r.target_commitish!==process.argv[4]||r.body!==process.argv[5]||r.draft!==true)process.exit(1)' "$r" "$CREATED_RELEASE_ID" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$(release_marker)"||return 1;api DELETE "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}";}
verify_uploaded_assets(){ local r;r="$(api GET "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}")";bun -e 'const r=JSON.parse(process.argv[1]),m=process.argv.slice(2).map(x=>{const [n,h]=x.split("=");return[n,h]});if(!r.draft||r.assets.length!==m.length)process.exit(1);for(const[n,h]of m){const a=r.assets.filter(x=>x.name===n);if(a.length!==1||a[0].digest!==`sha256:${h}`)process.exit(1)}' "$r" "${UPLOAD_EXPECTED[@]}"||release_error "uploaded assets differ by name/hash";}
publish_release(){ assert_github_only_environment;validate_inputs;verify_seal "$PUBLICATION_MANIFEST";[[ "$(sed -n 1p "$ATTESTATION_MARKER")" == "$(sha256_file "$PUBLICATION_MANIFEST")" ]]||release_error "attestation binding changed";validate_remote_annotated_tag;assert_release_absent;validate_monotonic_release;assert_no_unrelated_same_uid_processes;local body response upload_url;body="$(release_marker)";response="$(api POST "/repos/${GITHUB_REPOSITORY}/releases" -f tag_name="$INDEX_RELEASE_TAG" -f target_commitish="$INDEX_RELEASE_COMMIT" -f name="Index for macOS $VERSION" -f body="$body" -F draft=true -F prerelease=false)"||release_error "private draft creation failed";CREATED_RELEASE_ID="$(bun -e 'const r=JSON.parse(process.argv[1]);if(!Number.isInteger(r.id)||!r.draft||r.tag_name!==process.argv[2]||r.target_commitish!==process.argv[3]||r.body!==process.argv[4]||typeof r.upload_url!=="string")process.exit(1);console.log(r.id)' "$response" "$INDEX_RELEASE_TAG" "$INDEX_RELEASE_COMMIT" "$body")"||release_error "draft response invalid";upload_url="$(bun -e 'console.log(JSON.parse(process.argv[1]).upload_url.replace(/\{.*$/,""))' "$response")";local f n h;UPLOAD_EXPECTED=();while read -r h f;do f="$REPO_ROOT/$f";n="$(basename "$f")";api POST "$upload_url?name=$n" -H 'Content-Type: application/octet-stream' --input "$f">/dev/null||{ cleanup_created_release;return 1;};UPLOAD_EXPECTED+=("$n=$h");done<"$PUBLICATION_MANIFEST";verify_uploaded_assets;validate_remote_annotated_tag;validate_monotonic_release;assert_no_unrelated_same_uid_processes;api PATCH "/repos/${GITHUB_REPOSITORY}/releases/${CREATED_RELEASE_ID}" -F draft:='false'>/dev/null;DRAFT_PUBLISHED=1;}
if [[ "${BUILD_RELEASE_SOURCE_ONLY:-}" == 1 ]];then trap - EXIT;return 0 2>/dev/null||exit 0;fi
case "${1:-}" in prepare)prepare_release;;authorize)authorize_release;;candidate)candidate_release;;record-attestation)shift;record_attestation "$@";;publish)publish_release;;assert-absence)assert_github_only_environment;assert_release_absent;;*)release_error "usage: prepare|authorize|candidate|record-attestation|publish|assert-absence";;esac
trap - EXIT;release_cleanup 0
