const CLI_STATE_PATTERN = /^[A-Za-z0-9_-]{32,128}$/;

/** Validated CLI browser-auth protocol request. */
export type CliAuthRequest = { protocolVersion: 2; callback: string; state: string };

/**
 * Accept only a bounded URL-safe one-time state generated by the local CLI.
 */
export function validateCliAuthState(value: string | null): string | null {
  return value && CLI_STATE_PATTERN.test(value) ? value : null;
}

/**
 * Accept only the loopback callback opened by the local Index CLI process.
 * Broad API credentials must never be redirected to caller-controlled origins.
 */
export function validateCliCallbackUrl(value: string | null): string | null {
  if (!value) return null;
  try {
    const url = new URL(value);
    const port = Number(url.port);
    const isLoopback = url.hostname === "127.0.0.1" || url.hostname === "[::1]";
    if (
      url.protocol !== "http:"
      || !isLoopback
      || !Number.isInteger(port)
      || port < 1
      || port > 65535
      || url.pathname !== "/callback"
      || url.username
      || url.password
      || url.search
      || url.hash
    ) {
      return null;
    }
    return url.toString();
  } catch {
    return null;
  }
}

/**
 * Parse the v2 CLI browser-auth request; every other shape is rejected.
 *
 * @param params - Auth-page query parameters.
 * @returns A validated v2 request, or null for every malformed mix.
 */
export function parseCliAuthRequest(params: URLSearchParams): CliAuthRequest | null {
  if (params.getAll('callback').length !== 1) return null;
  const callback = validateCliCallbackUrl(params.get('callback'));
  if (!callback) return null;

  const versions = params.getAll('version');
  const states = params.getAll('state');
  if (versions.length !== 1 || versions[0] !== '2' || states.length !== 1) return null;
  const state = validateCliAuthState(states[0]);
  return state ? { protocolVersion: 2, callback, state } : null;
}

/**
 * Preserve the exact validated protocol request through web login — used as
 * the Better Auth callbackURL for the inline sign-in form on /cli-auth.
 *
 * @param pathname - CLI auth page pathname.
 * @param request - Validated versioned CLI auth request.
 * @returns Same-origin relative return path for the auth page.
 */
export function buildCliAuthReturnPath(
  pathname: string,
  request: CliAuthRequest,
): string {
  const returnUrl = new URL(pathname, 'https://index.local');
  returnUrl.searchParams.set('callback', request.callback);
  returnUrl.searchParams.set('version', '2');
  returnUrl.searchParams.set('state', request.state);
  return `${returnUrl.pathname}${returnUrl.search}`;
}

/**
 * Build the credential callback without interpolating untrusted URL text.
 *
 * @param validatedCallback - Callback accepted by validateCliCallbackUrl.
 * @param state - State accepted by validateCliAuthState.
 * @param apiKey - Newly minted API-key secret.
 * @param keyId - Exact `apikey` row ID.
 * @returns A loopback callback carrying the bound credential fields.
 */
export function buildCliApiKeyCallbackUrl(
  validatedCallback: string,
  state: string,
  apiKey: string,
  keyId: string,
): string {
  const callback = new URL(validatedCallback);
  callback.searchParams.set("api_key", apiKey);
  callback.searchParams.set("key_id", keyId);
  callback.searchParams.set("state", state);
  return callback.toString();
}
