name: deploy
on:
  push:
    branches: dev
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Install kubectl
        uses: azure/setup-kubectl@v2.0
        with:
          version: 'v1.23.6' # default is latest stable
        id: install       

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - run: |-
          aws eks --region us-east-1 update-kubeconfig --name indexas

      - name: Check k8s connection
        run: kubectl get pods   

      - name: Store build time
        id: build-time
        shell: bash
        run: >-
          echo "::set-output name=time::$(date +%s)"

      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          DOCKER_TAG: indexas/web3-web-app:${{ steps.build-time.outputs.time }}
          DOCKER_REGISTRY: 534970752686.dkr.ecr.us-east-1.amazonaws.com
        run: |
          docker build -t $DOCKER_TAG .
          docker tag $DOCKER_TAG $DOCKER_REGISTRY/$DOCKER_TAG
          docker push $DOCKER_REGISTRY/$DOCKER_TAG
          docker tag $DOCKER_TAG $DOCKER_REGISTRY/indexas/web3-web-app:latest
          docker push $DOCKER_REGISTRY/indexas/web3-web-app:latest 

      - name: Deploy
        run: |-
          kubectl set image deployment/web3-web-app web3-web-app=534970752686.dkr.ecr.us-east-1.amazonaws.com/indexas/web3-web-app:${{ steps.build-time.outputs.time }} --namespace testnet